// @vitest-environment jsdom
//
// ready-daf — WHEN THE RELAY WITHHOLDS THE GRANTS, THE BOARD FAILS CLOSED.
//
// THE DEFECT THIS PINS. Whether a board is confidential used to be derived
// ENTIRELY from relay-supplied kind-39301 owner grants, and their ABSENCE read
// as "public": BoardKeyring.cutover() returned null, main.ts's
// encryptedBoardsOf reported `ok:false`, envelope.ts's shouldQuarantine went
// inert, and the page rendered post-cutover CLEARTEXT with no notice
// distinguishing the board from one that was never confidential. Reads on this
// transport are unrestricted BY DESIGN and no relay is obliged to serve every
// event it holds, so omitting a handful of small events silently downgraded a
// confidential board in the reader's browser — the same relay-omission-as-attack
// shape as ready-dd5.
//
// WHAT THE FIXTURE DOES. It is the SAME Go-signed confidential board every other
// suite uses (lib/confidential.fixtures.ts, generated by the real
// pkg/sync writer), minus the grants. Nothing is faked beyond the relay
// transport and the extension: the sealed cards are really sealed, conf-005's
// cleartext is really signed by the real owner, and conf-006 really does predate
// the cutover. Only the grant events are gone, which is exactly the one thing a
// hostile-or-lossy relay controls.
//
// EVERY CASE HERE IS PAIRED WITH ITS OPPOSITE, because a fold that quarantined
// EVERYTHING would satisfy the closed assertions on its own: the same board with
// its grants served must still admit conf-006 and say nothing about an
// unestablished state, and a board with no confidential evidence at all must
// still render as an ordinary plaintext board.

import { beforeEach, describe, expect, it } from "vitest";
import { afterLogin, type BoardDeps, type Identity } from "./main";
import { authTransition } from "./lib/auth";
import { fakeNip44Signer } from "./lib/fakesigner";
import { nip07KeyUnwrapper, neverUnwraps } from "./lib/keyunwrap";
import { PLACEHOLDER } from "./lib/envelope";
import { hexToBytes } from "./lib/sha256";
import { tagValue, type NostrEvent } from "./lib/nostrevent";
import type { FragmentKeys, ParsedFragment } from "./lib/fragment";
import {
  BOARD_COORD,
  CEK_EPOCH1,
  CEK_EPOCH2,
  MEMBER_PUB,
  MEMBER_SEC,
  OWNER_PUB,
  STRANGER_PUB,
  STRANGER_SEC,
  boardEvent,
  cardEpoch1A,
  cardForgedSignature,
  cardGrandfatheredPlaintext,
  cards,
  expectedPlaintext,
  grants,
} from "./lib/confidential.fixtures";

/** The whole board with its OWNER GRANTS OMITTED — the one event class a relay
 * can drop without forging anything. */
const WITHHELD: NostrEvent[] = [boardEvent, ...cards];

/** The same board with everything served. The control. */
const SERVED: NostrEvent[] = [boardEvent, ...grants, ...cards];

/**
 * The cards in `cards` that a fail-CLOSED gate must still admit: every
 * well-formed SEALED envelope whose signature verifies. With the cutover
 * unestablished nothing else survives — no plaintext card can be grandfathered,
 * and the forged-signature card is dropped before the gate sees it.
 *
 * DERIVED, NOT HARDCODED, and the reason matters. `cards` is a fixture several
 * items share and legitimately extend: ready-02e added two more sealed cards
 * after this suite was written, and every hardcoded total here went red for a
 * reason that had nothing to do with confidentiality. A magic number invites the
 * next person to bump it back to green, which is precisely how a fail-closed
 * assertion stops being one. So the RULE is asserted and the count follows it;
 * SEALED_ADMITTED_IDS below is anchored against the ids known when this was
 * written, so the derivation cannot go vacuous.
 */
const SEALED_ADMITTED = cards.filter((c) => tagValue(c, "enc") === "1" && c.id !== cardForgedSignature.id);
const SEALED_ADMITTED_IDS = SEALED_ADMITTED.map((c) => tagValue(c, "d")).sort();

it("FIXTURE INVARIANT: the admitted set is the sealed, signature-valid cards and nothing else", () => {
  // Anchors the derivation. The four original sealed cards must be in it; the
  // two plaintext ones and the forged one must not — whatever else `cards`
  // grows. Without this the count assertions below could be satisfied by an
  // empty set.
  for (const id of ["conf-001", "conf-002", "conf-003", "conf-004"]) {
    expect(SEALED_ADMITTED_IDS).toContain(id);
  }
  expect(SEALED_ADMITTED_IDS).not.toContain(tagValue(cardGrandfatheredPlaintext, "d"));
  expect(SEALED_ADMITTED_IDS).not.toContain(tagValue(cardForgedSignature, "d"));
  expect(SEALED_ADMITTED_IDS).not.toContain("conf-005");
  expect(new Set(SEALED_ADMITTED_IDS).size).toBe(SEALED_ADMITTED_IDS.length);
});

let root: HTMLElement;

beforeEach(() => {
  document.body.replaceChildren();
  root = document.createElement("div");
  root.id = "app";
  document.body.append(root);
});

function signingIdentity(pubkey: string): Identity {
  return { pubkey, auth: authTransition({ type: "login", method: "extension" }) };
}

function readOnlyIdentity(pubkey: string): Identity {
  return { pubkey, auth: authTransition({ type: "login", method: "readOnly" }) };
}

/** deps serves `snapshot` for every REQ (a relay honours no filter it does not
 * feel like honouring) and wires the signer for `secretHex`, or none at all. */
function deps(snapshot: NostrEvent[], secretHex: string | null): BoardDeps {
  return {
    loadRelays: async () => ["wss://relay.test"],
    fetchEvents: async () => snapshot,
    keyUnwrapper: () => (secretHex === null ? neverUnwraps : nip07KeyUnwrapper(fakeNip44Signer(secretHex))),
  };
}

const boardFragment: ParsedFragment = { kind: "board", board: BOARD_COORD, relays: ["wss://relay.test"] };

/** What `rd board --with-key` puts in the link: both held epochs for this
 * board. Reader-side, relay-independent key material. */
function bothEpochKeys(): FragmentKeys {
  return {
    ceks: [
      { epoch: 1, key: hexToBytes(CEK_EPOCH1) },
      { epoch: 2, key: hexToBytes(CEK_EPOCH2) },
    ],
  };
}

function keyFragment(): ParsedFragment {
  return {
    kind: "board",
    board: BOARD_COORD,
    relays: ["wss://relay.test"],
    viewer: OWNER_PUB,
    keys: bothEpochKeys(),
  };
}

function renderedItems(): { id: string; title: string; sealed: boolean }[] {
  return [...root.querySelectorAll(".card[data-id]")].map((card) => ({
    id: card.querySelector(".card-id")?.textContent ?? "",
    title: card.querySelector(".card-title")?.textContent ?? "",
    sealed: card.classList.contains("sealed"),
  }));
}

const pageText = () => root.textContent ?? "";
const notice = () => root.querySelector(".confidential-notice")?.textContent ?? "";
/** The left tree's "Everything" count — the whole ADMITTED item set, including
 * terminal items that have no column and so render no card. This is the number
 * the fold gate moves, and the only place a quarantined `done` item shows up. */
const everythingCount = () => root.querySelector('.left-tree .node[data-scope=""] .ct')?.textContent;

describe("grants withheld: the confidentiality state is UNKNOWN and fails CLOSED", () => {
  it("still withholds the post-cutover cleartext card (the fail-open this item fixes)", async () => {
    await afterLogin(root, signingIdentity(STRANGER_PUB), boardFragment, deps(WITHHELD, STRANGER_SEC));

    // Before the fix this card rendered, title and body, on a board labelled
    // nothing at all. It is signed by the REAL board owner, so no signature
    // check stops it — only the fold gate does, and the gate is only on because
    // the sealed cards established the board is confidential.
    expect(renderedItems().map((i) => i.id)).not.toContain("conf-005");
    expect(pageText()).not.toContain("SMUGGLED CLEARTEXT TITLE");
    expect(pageText()).not.toContain("SMUGGLED CLEARTEXT BODY");
  });

  it("withholds the pre-cutover plaintext card too, because the cutover is UNESTABLISHED", async () => {
    await afterLogin(root, signingIdentity(STRANGER_PUB), boardFragment, deps(WITHHELD, STRANGER_SEC));

    // conf-006 is a legitimate grandfathered card — with the grants served it is
    // admitted (see the control below). Without them there is no cutover instant
    // to compare its created_at against, so "published before the board went
    // confidential" is not a claim this page can make about it, and fail-closed
    // means withholding rather than guessing.
    //
    // ASSERTED AS A COUNT, NOT AS ABSENT TEXT (the ready-56b lesson): conf-006's
    // status is `done` and a terminal item has no column, so its title is not on
    // the page even when it IS admitted — `not.toContain("Legacy plaintext
    // card")` would pass either way and prove nothing. The admitted-set count is
    // the number the gate actually moves: exactly the sealed cards here, one
    // MORE with the grants served (see the control below), the extra one being
    // conf-006. That difference of one is the assertion.
    //
    // Every sealed card admitted, conf-005 + conf-006 quarantined, conf-007
    // dropped for its forged signature.
    expect(everythingCount()).toBe(String(SEALED_ADMITTED.length));
  });

  it("says the confidentiality state could not be established, and names the board", async () => {
    await afterLogin(root, signingIdentity(STRANGER_PUB), boardFragment, deps(WITHHELD, STRANGER_SEC));

    const text = notice();
    expect(text).toContain("CONFIDENTIALITY STATE COULD NOT BE ESTABLISHED");
    expect(text).toContain("Confidential Board");
    // The two claims that must be present because either alone misleads: the
    // board IS confidential, and this view is NOT complete.
    expect(text).toContain("confidential");
    expect(text).toMatch(/WITHHELD from this view/);
    expect(text).toContain("do not read it as a public board");
  });

  it("does NOT claim the owner published no grant — only that none reached this page", async () => {
    // The wording rule unservedBoardsNotice already follows (ready-5c5): a
    // relay's silence is not evidence about the relay's contents, let alone
    // about what the owner published.
    await afterLogin(root, signingIdentity(STRANGER_PUB), boardFragment, deps(WITHHELD, STRANGER_SEC));
    const text = notice();
    expect(text).toContain("served by the relays this page reached");
    expect(text).toContain("A missing event is not evidence");
  });

  it("still shows the board's SHAPE — sealed placeholders, not an empty page and not an error", async () => {
    await afterLogin(root, signingIdentity(STRANGER_PUB), boardFragment, deps(WITHHELD, STRANGER_SEC));

    const items = renderedItems();
    // The rendered set is exactly the sealed, signature-valid cards — anchored
    // by the FIXTURE INVARIANT above, so this cannot be satisfied by an empty
    // or drifting expectation.
    expect(items.map((i) => i.id).sort()).toEqual(SEALED_ADMITTED_IDS);
    for (const i of items) {
      expect(i.title).toBe(PLACEHOLDER);
      expect(i.sealed).toBe(true);
    }
    for (const want of expectedPlaintext) {
      expect(pageText()).not.toContain(want.title);
      expect(pageText()).not.toContain(want.context);
    }
  });

  it("holds even for a MEMBER whose own grant was among the withheld events", async () => {
    // The member's extension is present and its key would open epochs 1 and 2 —
    // but the wraps live inside the grants, so withholding them takes the keys
    // away too. The board must fail closed for this reader exactly as for a
    // stranger, and must not report itself public just because a signer exists.
    await afterLogin(root, signingIdentity(MEMBER_PUB), boardFragment, deps(WITHHELD, MEMBER_SEC));

    for (const i of renderedItems()) expect(i.title).toBe(PLACEHOLDER);
    expect(pageText()).not.toContain("SMUGGLED CLEARTEXT TITLE");
    expect(notice()).toContain("CONFIDENTIALITY STATE COULD NOT BE ESTABLISHED");
  });

  it("holds for a read-only npub with no extension at all", async () => {
    await afterLogin(root, readOnlyIdentity(MEMBER_PUB), boardFragment, deps(WITHHELD, null));
    expect(pageText()).not.toContain("SMUGGLED CLEARTEXT TITLE");
    expect(notice()).toContain("CONFIDENTIALITY STATE COULD NOT BE ESTABLISHED");
  });
});

describe("ANTI-TAUTOLOGY: with the grants served, nothing is over-withheld", () => {
  it("admits the grandfathered card and says nothing about an unestablished state", async () => {
    await afterLogin(root, signingIdentity(MEMBER_PUB), boardFragment, deps(SERVED, MEMBER_SEC));

    // The established path is unchanged: cutover known, conf-006 grandfathered
    // in, conf-005 still quarantined. If this went red the fix would be
    // quarantining boards wholesale rather than reacting to unestablished state.
    // EXACTLY ONE more than the withheld case: conf-006, grandfathered on a
    // cutover that is now known.
    expect(everythingCount()).toBe(String(SEALED_ADMITTED.length + 1));
    expect(notice()).not.toContain("COULD NOT BE ESTABLISHED");
    expect(notice()).toContain("titles were decrypted in your browser");
    expect(pageText()).not.toContain("SMUGGLED CLEARTEXT TITLE");
  });

  it("a board with NO confidential evidence at all still renders as plaintext", async () => {
    // The stated limit of what a browser can establish, pinned so nobody
    // "hardens" it into quarantining every board that has no grants — which is
    // every ordinary solo board, since `rd grant` is what publishes a grant.
    //
    // This relay serves the board definition and ONE plaintext card: no grants,
    // no sealed cards, nothing that says the board was ever confidential. There
    // is no proof-of-non-omission in NIP-01, so this page cannot distinguish
    // "public board" from "confidential board whose every sealed card was ALSO
    // withheld", and it does not pretend to. What ready-daf fixes is the case
    // where evidence DID arrive and was ignored.
    await afterLogin(
      root,
      signingIdentity(STRANGER_PUB),
      boardFragment,
      deps([boardEvent, cardGrandfatheredPlaintext], STRANGER_SEC),
    );

    // ADMITTED — count, not title text: conf-006 is `done` and terminal items
    // have no column (see the count comment above).
    expect(everythingCount()).toBe("1");
    expect(notice()).not.toContain("COULD NOT BE ESTABLISHED");
  });
});

describe("grants withheld, but the LINK carries the read key", () => {
  // The ready-336 shape: the reader holds relay-independent key material minted
  // by their own rd, so the titles open — and before ready-daf the page then
  // presented those decrypted titles with NO confidentiality notice whatsoever,
  // because `confidential` was derived from grant-supplied cutovers alone. A
  // link that carries a board's read key is itself a statement that the board
  // HAS one.
  it("decrypts what the link's keys open", async () => {
    await afterLogin(root, readOnlyIdentity(OWNER_PUB), keyFragment(), deps(WITHHELD, null));
    const byId = new Map(renderedItems().map((i) => [i.id, i]));
    expect(byId.get("conf-001")?.title).toBe(expectedPlaintext[0].title);
    expect(byId.get("conf-003")?.title).toBe(expectedPlaintext[2].title);
  });

  it("labels the board confidential AND unestablished anyway", async () => {
    await afterLogin(root, readOnlyIdentity(OWNER_PUB), keyFragment(), deps(WITHHELD, null));
    expect(notice()).toContain("titles were decrypted in your browser");
    expect(notice()).toContain("CONFIDENTIALITY STATE COULD NOT BE ESTABLISHED");
  });

  it("keeps the quarantine on: a key is not a cutover", async () => {
    await afterLogin(root, readOnlyIdentity(OWNER_PUB), keyFragment(), deps(WITHHELD, null));
    // Link keys add reading power; they establish no instant, so the smuggled
    // cleartext stays out and the grandfathered card stays out with it — the
    // sealed cards only, not those plus the two plaintext ones.
    expect(pageText()).not.toContain("SMUGGLED CLEARTEXT TITLE");
    expect(everythingCount()).toBe(String(SEALED_ADMITTED.length));
  });

  it("a link key alone is enough evidence even when every sealed card is withheld too", async () => {
    // Relay serves the definition, one pre-cutover plaintext card and NO sealed
    // cards — the shape that defeats the sealed-card witness. The link's key is
    // the second, relay-independent witness, so the gate is still on.
    await afterLogin(
      root,
      readOnlyIdentity(OWNER_PUB),
      keyFragment(),
      deps([boardEvent, cardGrandfatheredPlaintext], null),
    );
    expect(notice()).toContain("CONFIDENTIALITY STATE COULD NOT BE ESTABLISHED");
    // Nothing admitted at all: the one card served is plaintext with no
    // establishable cutover to grandfather it against. Contrast the same relay
    // WITHOUT the link's keys, which admits it (previous describe block).
    expect(everythingCount()).toBe("0");
  });
});

describe("evidence is taken only from VERIFIED events", () => {
  it("a tampered sealed card cannot be the thing that establishes confidentiality", async () => {
    // Same rule as deriveBoardKeyring's CHECK 1: a relay is untrusted, so an
    // event whose signature does not verify witnesses nothing in EITHER
    // direction. Here the only enc-marked event on the board is a mutated copy
    // of a real sealed card; with no valid sealed card and no grants there is no
    // evidence, so the board reads as plaintext and its plaintext card renders.
    // (Fail-closed is about what a valid signature says, not about treating
    // garbage as authority — otherwise any relay could quarantine any board by
    // appending one junk event.)
    const tampered: NostrEvent = { ...cardEpoch1A, content: cardEpoch1A.content.replace(/^./, "A") };
    await afterLogin(
      root,
      signingIdentity(STRANGER_PUB),
      boardFragment,
      deps([boardEvent, cardGrandfatheredPlaintext, tampered], STRANGER_SEC),
    );

    expect(renderedItems().map((i) => i.id)).not.toContain("conf-001");
    expect(notice()).not.toContain("COULD NOT BE ESTABLISHED");
    // The plaintext card is admitted (count, not title text — it is terminal).
    expect(everythingCount()).toBe("1");
  });
});
