// writeevents.vectors.test.ts — ready-b2b done-condition 3: the browser's write
// path replays testdata/write.vectors.json, THE SAME FILE cmd/rd's suite runs
// (cmd/rd/writevectors_test.go), and must reproduce every pinned event
// byte-for-byte: kind, the FULL tag array in the exact emission order (§19.5),
// and content.
//
// It is deliberately the same file, not a copy. A copy would drift, and drift is
// precisely the failure this milestone exists to prevent — the client and rd
// silently disagreeing about event shape. If a vector fails here, the BROWSER is
// wrong: the vector is what rd's real writer actually emits (it is generated by
// replaying rd's own un-exported run*Nostr bodies), so never edit the vector to
// make this pass.
//
// It also replays the round-trip: the produced events are REALLY SIGNED (a real
// secp256k1 key via schnorrsign.ts) and folded back through the shipped
// projection (lib/fold.ts's projectItems, the TS mirror of pkg/sync.ProjectItems
// that internal/foldvectors pins) and compared against the vector's post_fold.
// A write the reader cannot read back is the failure the whole item exists to
// prevent.
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { projectItems, KindCard, KindIssue } from "../lib/fold";
import type { NostrEvent } from "../lib/nostrevent";
import { tagValue } from "../lib/nostrevent";
import { signNostrEvent, xOnlyPubkey } from "../lib/schnorrsign";
import type { Item } from "../lib/state";
import { StatusInbox } from "../lib/state";
import {
  boardCoord,
  buildFullCreate,
  buildWrite,
  WriteRefusedError,
  type BuiltEvent,
  type WriteEnv,
  type WriteOp,
} from "./writeevents";

const VECTOR_PATH = path.resolve(import.meta.dirname, "../../../../testdata/write.vectors.json");

// The same fixed board-d every committed vector's "a" tags hardcode — see the
// vector file's "compared" note and writeVectorProject's assertion on the Go
// side (setupNostrCmdTest always names the project directory "project").
const BOARD_D = "project";

// A real, fixed test key. The vectors compare tag VALUES, and every value that
// depends on the signing key is templated as {{owner}} and substituted with this
// key's pubkey — exactly what the Go harness does with its per-run key.
const SECRET = "b7e151628aed2a6abf7158809cf4f3c762e7160f38b4da56a784d9045190cfef";
const OWNER = xOnlyPubkey(SECRET);

interface ContentShape {
  mode: string;
  value?: string;
}
interface EventExpect {
  kind: number;
  tags: string[][];
  content: ContentShape;
}
interface ItemFixture {
  id: string;
  title?: string;
  context?: string;
  type?: string;
  priority?: string;
  status?: string;
  by?: string;
  for?: string;
  level?: string;
  parent_id?: string;
  eta?: string;
  due?: string;
  labels?: string[];
  blocked_by?: string[];
  gate?: string;
  waiting_type?: string;
  waiting_on?: string;
}
interface Vector {
  name: string;
  op: string;
  args?: Record<string, string>;
  seed?: ItemFixture;
  extra_seeds?: ItemFixture[];
  events?: EventExpect[];
  expect_error?: boolean;
  error_contains?: string;
  post_fold?: ItemFixture;
}

const vectorFile = JSON.parse(readFileSync(VECTOR_PATH, "utf8")) as {
  version: number;
  vectors: Vector[];
};

/** itemFromFixture mirrors the Go harness's seedItem: Status defaults to inbox
 * and For defaults to the signer, so a hand-seeded fixture carries the same
 * "for" tag any real `rd create` item does. */
function itemFromFixture(f: ItemFixture): Item {
  return {
    id: f.id,
    msg_id: "",
    title: f.title ?? "",
    context: f.context ?? "",
    type: f.type ?? "",
    priority: f.priority ?? "",
    status: f.status ?? StatusInbox,
    by: f.by || undefined,
    for: f.for || OWNER,
    level: f.level || undefined,
    parent_id: f.parent_id || undefined,
    eta: f.eta || undefined,
    due: f.due || undefined,
    labels: f.labels,
    blocked_by: f.blocked_by,
    gate: f.gate || undefined,
    waiting_type: f.waiting_type || undefined,
    waiting_on: f.waiting_on || undefined,
    created_at: 0n,
    updated_at: 0n,
  };
}

/** A replay log: signed events in append order, exactly like .ready/nostr-log.jsonl. */
class ReplayLog {
  readonly events: NostrEvent[] = [];
  private clock = 1_780_000_000;

  /** nextCreatedAt mirrors cmd/rd's nostrNextCreatedAt scoped to ONE item's
   * causal chain (§17.2): strictly after the newest event already in that
   * chain, so two writes in the same wall-clock second still order by intent. */
  nextCreatedAt(itemId: string): number {
    let max = 0;
    for (const e of this.events) {
      if (driftScope(e) !== `item:${itemId}`) continue;
      if (e.created_at > max) max = e.created_at;
    }
    return max + 1 > this.clock ? max + 1 : this.clock;
  }

  append(built: BuiltEvent[]): NostrEvent[] {
    const signed = built.map((b) =>
      signNostrEvent({ created_at: b.created_at, kind: b.kind, tags: b.tags, content: b.content }, SECRET),
    );
    // The id the builder computed must be the id the signer produced — the
    // whole status-event anchor depends on it.
    signed.forEach((s, i) => expect(s.id).toBe(built[i].id));
    this.events.push(...signed);
    return signed;
  }

  issueEventIds(): Map<string, string> {
    const out = new Map<string, string>();
    for (const e of this.events) {
      if (e.kind === KindIssue) {
        const d = tagValue(e, "d");
        if (d !== "") out.set(d, e.id);
      }
    }
    return out;
  }

  project(): Map<string, Item> {
    return projectItems(this.events, {
      trusted: null,
      maintainers: null,
      pinnedBoard: boardCoord(OWNER, BOARD_D),
      decryptor: null,
      encryptedBoards: null,
    });
  }
}

function driftScope(e: NostrEvent): string {
  if (e.kind === KindCard || e.kind === KindIssue || (e.kind >= 1630 && e.kind <= 1632)) {
    const d = tagValue(e, "d");
    if (d !== "") return `item:${d}`;
  }
  return "";
}

function envFor(log: ReplayLog, itemId: string): WriteEnv {
  return {
    signer: OWNER,
    boardAuthor: OWNER,
    boardD: BOARD_D,
    boardTitle: BOARD_D,
    items: log.project(),
    issueEventIds: log.issueEventIds(),
    createdAt: log.nextCreatedAt(itemId),
  };
}

function seed(log: ReplayLog, f: ItemFixture): void {
  const item = itemFromFixture(f);
  log.append(buildFullCreate(envFor(log, f.id), item));
}

/** opFor maps a vector's (op, args) onto the browser's intent type — the direct
 * counterpart of dispatchWriteVectorOp's switch on the Go side. */
function opFor(v: Vector, targetId: string): WriteOp {
  const a = v.args ?? {};
  switch (v.op) {
    case "create":
      return { op: "create", id: a.id, title: a.title, context: a.context, type: a.type, priority: a.priority };
    case "claim":
      return { op: "claim", itemId: targetId, reason: a.reason };
    case "close":
      return { op: "close", itemId: targetId, resolution: a.resolution, reason: a.reason };
    case "delegate":
      return { op: "delegate", itemId: targetId, to: a.to, reason: a.reason };
    case "gate_open":
      return { op: "gate_open", itemId: targetId, gateType: a.gate_type, description: a.description };
    case "gate_approve":
      return { op: "gate_approve", itemId: targetId, reason: a.reason };
    case "gate_reject":
      return { op: "gate_reject", itemId: targetId, reason: a.reason };
    case "dep_add":
      return { op: "dep_add", itemId: targetId, blockerId: a.blocker_id };
    case "dep_remove":
      return { op: "dep_remove", itemId: targetId, blockerId: a.blocker_id };
    case "label_add":
      return { op: "label_add", itemId: targetId, label: a.label };
    case "label_remove":
      return { op: "label_remove", itemId: targetId, label: a.label };
    case "update_fields":
      return {
        op: "update_fields",
        itemId: targetId,
        title: a.title,
        context: a.context,
        priority: a.priority,
        eta: a.eta,
        due: a.due,
        level: a.level,
        parentId: a.parent_id,
      };
    case "update_status":
      return {
        op: "update_status",
        itemId: targetId,
        statusTo: a.status_to,
        waitingOn: a.waiting_on,
        waitingType: a.waiting_type,
        note: a.note,
      };
    default:
      throw new Error(`vector ${v.name}: unknown op ${v.op} — add it to opFor`);
  }
}

/** out0 replaces every occurrence of a LITERAL token (no regex semantics), the
 * same substitution expandPlaceholders does on the Go side. */
function out0(s: string, token: string, value: string): string {
  return s.split(token).join(value);
}

function expandPlaceholders(s: string, cardIds: Map<string, string>, issueIds: Map<string, string>): string {
  let out = out0(s, "{{owner}}", OWNER);
  for (const [id, cid] of cardIds) out = out0(out, `{{card:${id}}}`, cid);
  for (const [id, iid] of issueIds) out = out0(out, `{{issue:${id}}}`, iid);
  return out;
}

describe(`write conformance vectors (${vectorFile.vectors.length} from testdata/write.vectors.json)`, () => {
  for (const v of vectorFile.vectors) {
    it(v.name, () => {
      const log = new ReplayLog();
      for (const es of v.extra_seeds ?? []) seed(log, es);
      if (v.seed) seed(log, v.seed);

      const before = log.events.length;
      const targetId = v.seed ? v.seed.id : (v.args?.item_id ?? v.args?.id ?? "");
      const env = envFor(log, targetId);

      let built: BuiltEvent[] | undefined;
      let opErr: unknown;
      try {
        built = buildWrite(env, opFor(v, targetId));
      } catch (err) {
        opErr = err;
      }

      if (v.expect_error) {
        expect(opErr, `expected a refusal containing ${v.error_contains}`).toBeInstanceOf(WriteRefusedError);
        expect(String((opErr as Error).message)).toContain(v.error_contains ?? "");
        // A refusal MUST NOT partially publish.
        expect(log.events.length).toBe(before);
        return;
      }
      if (opErr) throw opErr;

      const signed = log.append(built!);

      // §19.7/§25.5: no live write ever carries a "by" tag — attribution is the
      // event's own pubkey, never a separate spoofable tag.
      for (const e of signed) {
        expect(e.tags.some((t) => t[0] === "by")).toBe(false);
      }

      const cardIds = new Map<string, string>();
      for (const e of signed) {
        if (e.kind === KindCard) {
          const d = tagValue(e, "d");
          if (d !== "") cardIds.set(d, e.id);
        }
      }
      const issueIds = log.issueEventIds();

      const want = v.events ?? [];
      expect(signed.map((e) => e.kind), "event kinds").toEqual(want.map((w) => w.kind));
      want.forEach((w, i) => {
        const got = signed[i];
        const wantTags = w.tags.map((t) => t.map((val) => expandPlaceholders(val, cardIds, issueIds)));
        expect(got.tags, `event ${i} (kind ${w.kind}) tags`).toEqual(wantTags);
        if (w.content.mode === "empty") expect(got.content, `event ${i} content`).toBe("");
        else if (w.content.mode === "literal") expect(got.content, `event ${i} content`).toBe(w.content.value);
        else throw new Error(`event ${i}: unknown content mode ${w.content.mode}`);
      });

      if (!v.post_fold) return;
      const items = log.project();
      const got = items.get(v.post_fold.id);
      expect(
        got,
        `round-trip: item ${v.post_fold.id} is absent from the projection of this vector's own produced log — ` +
          `a write the reader cannot read back is exactly the failure this suite exists to catch`,
      ).toBeDefined();
      const pf = v.post_fold;
      if (pf.status) expect(got!.status, "post-fold status").toBe(pf.status);
      if (pf.title) expect(got!.title, "post-fold title").toBe(pf.title);
      if (pf.priority) expect(got!.priority, "post-fold priority").toBe(pf.priority);
      if (pf.context) expect(got!.context, "post-fold context").toBe(pf.context);
      if (pf.by) expect(got!.by, "post-fold by").toBe(expandPlaceholders(pf.by, cardIds, issueIds));
      if (pf.gate) expect(got!.gate, "post-fold gate").toBe(pf.gate);
      if (pf.waiting_type) expect(got!.waiting_type, "post-fold waiting_type").toBe(pf.waiting_type);
      if (pf.labels) expect([...(got!.labels ?? [])].sort(), "post-fold labels").toEqual([...pf.labels].sort());
      if (pf.blocked_by)
        expect([...(got!.blocked_by ?? [])].sort(), "post-fold blocked_by").toEqual([...pf.blocked_by].sort());
    });
  }
});

describe("same-second writes to the same item are strictly ordered (§17.2/§17.3)", () => {
  it("two back-to-back writes get strictly increasing created_at, later wins", () => {
    const log = new ReplayLog();
    seed(log, { id: "wv-mono", title: "monotonic", type: "task", priority: "p2" });
    log.append(buildWrite(envFor(log, "wv-mono"), { op: "claim", itemId: "wv-mono", reason: "first" }));
    log.append(
      buildWrite(envFor(log, "wv-mono"), {
        op: "update_status",
        itemId: "wv-mono",
        statusTo: "waiting",
        waitingType: "vendor",
        note: "second",
      }),
    );
    const stamps = log.events
      .filter((e) => e.kind === 1630 && tagValue(e, "d") === "wv-mono")
      .map((e) => e.created_at);
    expect(stamps.length).toBe(3); // create's status(inbox) + claim + update
    for (let i = 1; i < stamps.length; i++) expect(stamps[i]).toBeGreaterThan(stamps[i - 1]);
    // The later write wins the read-side tiebreak.
    expect(log.project().get("wv-mono")!.status).toBe("waiting");
  });
});
