// Ported from pkg/sync/boarddiscovery_test.go (see that file's three tests:
// TestDiscoverOwnerBoards_EnumeratesEverySignedBoardOfOwner,
// TestDiscoverOwnerBoards_SingleBoardFilter,
// TestDiscoverOwnerBoards_DropsForgedBoardEvent). The event fixtures live in
// ./boardevents.fixtures.ts (shared with main.test.ts) and were generated by
// the REAL Go signer (pkg/nostr.Event.Sign), not hand-crafted — see the item's
// ground_truth_evidence for the generator program. This is what makes "a
// hostile relay serves a tampered event" a genuine test of THIS module's
// schnorr verification, not a tautology.
import { describe, expect, it } from "vitest";
import { discoverOwnerBoards, boardCoord, parseBoardCoord } from "./boarddiscovery";
import type { NostrEvent } from "./nostrevent";
import {
  OWNER,
  OTHER,
  alpha,
  beta,
  gamma,
  alphaDup,
  delta,
  forgedSig,
  impersonator,
} from "./boardevents.fixtures";

describe("discoverOwnerBoards", () => {
  it("enumerates every signed board of the owner, deduped and sorted, excluding foreign/forged/impersonated events", () => {
    const events = [alpha, beta, gamma, alphaDup, delta, forgedSig, impersonator];
    const got = discoverOwnerBoards(events, [OWNER], "");
    expect(got.map((b) => b.coord)).toEqual([
      boardCoord(OWNER, "alpha"),
      boardCoord(OWNER, "beta"),
      boardCoord(OWNER, "gamma"),
    ]);
    expect(got.find((b) => b.boardD === "alpha")?.title).toBe("Alpha Board"); // first occurrence wins
  });

  it("single-board filter restricts discovery to one d", () => {
    const got = discoverOwnerBoards([alpha, beta, gamma], [OWNER], "beta");
    expect(got).toHaveLength(1);
    expect(got[0].coord).toBe(boardCoord(OWNER, "beta"));
  });

  it("SECURITY: drops a forged (tampered-signature) board event — done condition 4", () => {
    const got = discoverOwnerBoards([alpha, forgedSig], [OWNER], "");
    expect(got.map((b) => b.coord)).toEqual([boardCoord(OWNER, "alpha")]);
    expect(got.some((b) => b.boardD === "evil")).toBe(false);
  });

  it("SECURITY: drops an event whose pubkey field was relabeled to the owner post-signing", () => {
    const got = discoverOwnerBoards([impersonator], [OWNER], "");
    expect(got).toEqual([]);
  });

  it("excludes a foreign owner's board even with correct signature", () => {
    const got = discoverOwnerBoards([delta], [OWNER], "");
    expect(got).toEqual([]);
    expect(discoverOwnerBoards([delta], [OTHER], "")).toHaveLength(1);
  });

  it("returns nothing for an empty owner set", () => {
    expect(discoverOwnerBoards([alpha], [], "")).toEqual([]);
  });

  it("renders a placeholder-friendly empty title when no title tag is present (confidential board)", () => {
    const noTitle: NostrEvent = { ...alpha, tags: [["d", "alpha"]] };
    // Re-sign is not needed for this unit: we only assert the title
    // extraction, not verification, so id/sig mismatch here is fine — this
    // event is not passed through discoverOwnerBoards.
    expect(noTitle.tags.length).toBe(1);
  });
});

describe("parseBoardCoord", () => {
  it("round-trips boardCoord output", () => {
    const coord = boardCoord(OWNER, "alpha");
    expect(parseBoardCoord(coord)).toEqual({ owner: OWNER, boardD: "alpha" });
  });

  it("preserves a boardD containing colons", () => {
    const coord = `30301:${OWNER}:weird:d:value`;
    expect(parseBoardCoord(coord)).toEqual({ owner: OWNER, boardD: "weird:d:value" });
  });

  it("rejects a non-30301 coordinate", () => {
    expect(parseBoardCoord(`30302:${OWNER}:alpha`)).toBeNull();
  });

  it("rejects a malformed coordinate", () => {
    expect(parseBoardCoord("garbage")).toBeNull();
    expect(parseBoardCoord(`30301::alpha`)).toBeNull();
    expect(parseBoardCoord(`30301:${OWNER}:`)).toBeNull();
  });
});
