import { describe, expect, it } from "vitest";
import { seal, open } from "./chacha20poly1305";
import { hexToBytes, bytesToHex } from "./sha256";

// Known-answer vector generated by the REAL Go dependency this module must
// match — golang.org/x/crypto/chacha20poly1305, called exactly the way
// pkg/sync/envelope.go's sealContent/openContent call it: aead.Seal(nil,
// nonce, plaintext, nil), i.e. NO additional data (matching this module's
// AAD-less seal/open — the fold never needs AEAD with AAD). Generating
// through the actual dependency (rather than transcribing the RFC 8439
// §2.8.2 vector, which carries a 12-byte AAD this envelope never uses) is
// what proves byte-for-byte parity with the thing being matched, not just
// RFC 8439 compliance in the abstract.
//
// Regeneration: `go run` a one-off program that imports
// golang.org/x/crypto/chacha20poly1305, calls aead.Seal(nil, nonce,
// plaintext, nil) with the key/nonce/plaintext below, and prints
// hex(ciphertext).
const KEY_HEX = "0101010101010101010101010101010101010101010101010101010101010101".slice(0, 64);
const NONCE_HEX = "020202020202020202020202";
const PLAINTEXT = '{"title":"Confidential title","context":"secret body","waiting_on":"","labels":["security"]}';
const CIPHERTEXT_HEX =
  "9d3e8647f9cf8df84b0faa96bded8d4de9dd1864e2c65da77df077d8d7ba66bfbc7d8d90437a2483f4b85a64f" +
  "aab5ac7ebfcbdab5812fd7d3331e8d207e246baed94b550d1ba38bb1d713d553c0b8ad4cb8aef4a8cf17806493" +
  "10463855ff95764c8db2000357b7e41cdf7d8";

describe("chacha20poly1305", () => {
  it("open() matches the Go-generated known-answer plaintext", () => {
    const key = hexToBytes(KEY_HEX);
    const nonce = hexToBytes(NONCE_HEX);
    const ciphertext = hexToBytes(CIPHERTEXT_HEX);
    const plaintext = open(key, nonce, ciphertext);
    expect(plaintext).not.toBeNull();
    expect(new TextDecoder().decode(plaintext!)).toBe(PLAINTEXT);
  });

  it("seal() reproduces the same Go-generated known-answer ciphertext", () => {
    const key = hexToBytes(KEY_HEX);
    const nonce = hexToBytes(NONCE_HEX);
    const ciphertext = seal(key, nonce, new TextEncoder().encode(PLAINTEXT));
    expect(bytesToHex(ciphertext)).toBe(CIPHERTEXT_HEX);
  });

  it("open() fail-closes (returns null, never throws) on a tampered tag", () => {
    const key = hexToBytes(KEY_HEX);
    const nonce = hexToBytes(NONCE_HEX);
    const ciphertext = hexToBytes(CIPHERTEXT_HEX);
    const tampered = ciphertext.slice();
    tampered[tampered.length - 1] ^= 0x01; // flip a bit in the tag
    expect(open(key, nonce, tampered)).toBeNull();
  });

  it("open() fail-closes on tampered ciphertext body (AEAD, not just confidentiality)", () => {
    const key = hexToBytes(KEY_HEX);
    const nonce = hexToBytes(NONCE_HEX);
    const ciphertext = hexToBytes(CIPHERTEXT_HEX);
    const tampered = ciphertext.slice();
    tampered[0] ^= 0x01;
    expect(open(key, nonce, tampered)).toBeNull();
  });

  it("open() fail-closes on the wrong key", () => {
    const wrongKey = hexToBytes("0202020202020202020202020202020202020202020202020202020202020202".slice(0, 64));
    const nonce = hexToBytes(NONCE_HEX);
    const ciphertext = hexToBytes(CIPHERTEXT_HEX);
    expect(open(wrongKey, nonce, ciphertext)).toBeNull();
  });
});
