// GENERATED by web/board/testdata/genconfidential/main.go — DO NOT EDIT BY HAND.
//
//	go run ./web/board/testdata/genconfidential/main.go > web/board/src/lib/confidential.fixtures.ts
//
// A complete confidential-board scenario produced by the REAL Go writer
// (pkg/sync BuildBoardEvent / BuildRoleGrantEvent / BuildCardEvent, pkg/nip44.Seal,
// and the ChaCha20-Poly1305 content envelope). Because every byte here came out of
// production Go, the browser suite that consumes it is a cross-implementation
// conformance test, not a self-consistency check: if the TypeScript envelope, the
// grant parser, the NIP-44 unwrap or the NIP-01 id/signature derivation drifts from
// Go, these tests go red.
//
// SECRET KEYS BELOW ARE TEST-ONLY, freshly generated by the generator run that
// produced this file. They exist so the browser suite can stand in for a NIP-07
// signer (which is the only thing that ever holds a secret key in production — see
// nip07.ts). Nothing here is production key material, and nothing in
// index.html -> main.ts imports this module, so it is never bundled into dist/.

import type { NostrEvent } from "./nostrevent";

export const BOARD_D = "confboard";
export const BOARD_COORD = "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard";
export const OWNER_PUB = "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5";
export const OWNER_SEC = "d9f1e622b579314a3f93e123493a6b0eecf662973dd8f14b6432a8c02cb1ed26";
export const MEMBER_PUB = "3be7a22c2cc01e01a87cf24ce1f528800715787ec1af5833cc1875cb51ef8091";
export const MEMBER_SEC = "3e8934bcf3a94ac2fe7a7c3b904084a596a601a4e04d9424e177bfddf7305648";
export const REVOKED_PUB = "0bf4479ce15352c68eeb581d3dfd2f408778c0397e58d586f7eee7fb46b1ce7a";
export const REVOKED_SEC = "454c05033353338c5dadef94e8dd5f4794c550c13e9f988baadd0bc764d7265a";
export const STRANGER_PUB = "8fc268e623e6386c7f63f8ec19b10cafadcffbd42919513c5a4c7af905551f76";
export const STRANGER_SEC = "72791386bc6a0fa6642ab238b40039152331ae44014c8eb637ec03ccaebfe8d8";

/** The board-global cutover (created_at of the first CEK-bearing owner grant). */
export const CUTOVER = 1750000100;

/** Raw epoch keys, exported so envelope-level tests can seal/open without a keyring. */
export const CEK_EPOCH1 = "3d4468516734e4c1e9c6eb9165312dc3d23cfaa67878b162cd2e76ffe6b18ce2";
export const CEK_EPOCH2 = "e38b4a1ee2588b6dc40c48f01af5a6db1a9891d828ea72cb6ae7b873210166e6";
export const LTK = "281311769255fef9a0ef246e745ecd2954dab329b080daf7fccaa9dce9b85a2d";

export const boardEvent: NostrEvent = {
  "id": "bf4f35e3c17bd7ee6334bcdcaeea374493c37bfe36cdbeb7e1d89ab088f9d0fe",
  "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
  "created_at": 1750000000,
  "kind": 30301,
  "tags": [
    [
      "d",
      "confboard"
    ],
    [
      "title",
      "Confidential Board"
    ]
  ],
  "content": "",
  "sig": "67904f397cf50d61831a9462501600a17b2b3575e2eaf38def5fb29a4ad82cb860a7e9e604ac42dd1a97e3aa2ae8d8736828764f0c5d5e2f0f092481bbe69f22"
};

export const grants: NostrEvent[] = [
  {
    "id": "87ae0801cb68d9fe911feb98577efc1f5d786622d9bc5ab80cd6fe852e799a97",
    "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5"
      ],
      [
        "p",
        "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5"
      ],
      [
        "a",
        "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AnS/wbkmNL+spvQM2GquwHjQ4sopCSPR7WdJC5DM0WUzKYos0ZAXMAusP6rV21YpUSs9ePav8HNUvdLYw1TOLzK5gRKJTEwK3jHRnmhwVDszLcsff64Qt8BhGM5N7Kl+6DyHOzw3284RvMBZLtfmP9ThIJiC8DiAxbp2s1iUzc3rdbk="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "ArNFM62NeJeNTr+tcqTd0uWcfC3SFHu78wX6V1bkWBwd5cYIZuAr5aovVOc5vVp6MLDjpAj6xLgW/WwVrLRU+cifaqwOxaVIDB9ioHaDXgwQRE2FQuyTK/brAJ0G/Gh1MtZpxt+sFCmVydxXZFcRZNusMoaJNK9WvbkTxryhe5JLGRk="
      ]
    ],
    "content": "",
    "sig": "a4eff01089be406e67cf544e6491ca6a4683af12561e75cd82460aa3af038ef0218de9345a37ffd303d3bf3374016d033517441b1b885c429c10eec0903c0fb9"
  },
  {
    "id": "85580ff990307c62bb7f2b1625c55c6d71e34b7c5be2b6f9518c2ccd6cbaf053",
    "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:3be7a22c2cc01e01a87cf24ce1f528800715787ec1af5833cc1875cb51ef8091"
      ],
      [
        "p",
        "3be7a22c2cc01e01a87cf24ce1f528800715787ec1af5833cc1875cb51ef8091"
      ],
      [
        "a",
        "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "AkyYP+GsAe3NddnL9ND+zHSNEU1H5cVkAfNxyPK/jfiBNZqrJHSqr9/44FpMccvQzzD4GGn0pH6VS+y9+syUjY+G5nRAZ7mzPUpnzoblnKtdlZbPg/ZsKSDSnkEcPgUPGLw9bJ3O4jO2WOawdH4ucjMd3c3slmso+qHIP87Dr3f7Tjc="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "At+9/GFlInVKeAOrrHSbmxsb2BU3DSssDxS/iRmIcuQBiEBeuclUJOUna8LCFw+WRPz7h59+s4pz4KljfLVKAXt178FFLjnVbSfm6xBYtgcPds2WVcgH0SZf8O3zkOyhYdwo7hDhTCuN0wunkHCAvqblaQO8gutZys1Kf48e1Vncb9Q="
      ]
    ],
    "content": "",
    "sig": "9154a1e1646c32d8d265e5768d2a261244acfab17229565eefd3ca40c366b7f1e1a19c265589e34550165793295833735e18caa5488be196dc17538f09699f75"
  },
  {
    "id": "5bef389060252bf126f96681afa2bdfa47cdec4767305db8976d6177e962179a",
    "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:0bf4479ce15352c68eeb581d3dfd2f408778c0397e58d586f7eee7fb46b1ce7a"
      ],
      [
        "p",
        "0bf4479ce15352c68eeb581d3dfd2f408778c0397e58d586f7eee7fb46b1ce7a"
      ],
      [
        "a",
        "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "AgQAXCHWcMRHcDzZxnzKdywl4YMGbmfdj/JthIWQuZmNqse3AhxpWnIkdl7z9MWA+9oNbrBovf85mzDlOMDDw5AxMZ3Z4zlvb3rL2leZpMkIRoc3kk5JMp45G9+3mR3bznzItgXYoglhzkQ9e+Cq+i9NA9dlJ3wZrdjMPh2gI0lxfpI="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "AqWxd3HlGc12mUPoI/j/olWGatXv78IsQcYZapU620krszp6EqsXe0Z/ZHaHyKxyF8TsCUglXWcZZdPb12cTWj9axS/zsMNzTnGITbl9jdoTsh6AlETxi/mCT/fqSGbbiVOa7TiiOwCjxZoz4UGZS3VTrcROCbIt7RJy1/yiEvX4bWA="
      ]
    ],
    "content": "",
    "sig": "cad18ce39c62a9b132fe60ce2a8a1e018dc54acc910c2f5f566e21492ae82b64ec6b4e4d724ff78d853bf995014b49085b06d9e56d2c6002e9dd7a5f325117c8"
  },
  {
    "id": "499f340be929651af3325bc546f2ae6aa596b3da8aaed1d97402473450cb439d",
    "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
    "created_at": 1750000310,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5"
      ],
      [
        "p",
        "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5"
      ],
      [
        "a",
        "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AjY4CP16oK63Cck+9H2c3J2Vv4K0dItG1rr9eeuJVL9kOeewkH6LOumL3nqe1u0cueuvWNLkhHAULOKVUt99DFocbKnMK3NQtA+42DU6gpxe14H5GHnjJ8UrfOe2sbESKiqHNyQ0u6LVShZTAXHwB0TeFxzoL8V8RCZaAx4arhNBau0="
      ],
      [
        "cek_epoch",
        "2"
      ],
      [
        "ltk",
        "Ahh2hI0pTmQK9SIrfX0wb7euD0WCjRlZc7gIlXc1pv/85rEkpsWPgyq5QoKfxctWN0Uy4v2wCDJaVEdO6KjmlfBewRsNl71mFQ22BDwGIz5XEO6TpaSt1+4cvbK/aCuOYvAU4jyQmbdzuzTkao9Y8RdX5adDtdOVDGC4pRdfTmcjdWE="
      ]
    ],
    "content": "",
    "sig": "1ef36096cdf1f1aa7342f22cceb2f6fe5132755270288d059c514335bdbdafa6099f1733ece9015f65b2ef768e51541283fcdf286f3f8051103dcdbe9f7ad6aa"
  },
  {
    "id": "293ec2dd3a09d7bbabda37b0e9791f753eddf0f02dd02e4e971d7f5c38965485",
    "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
    "created_at": 1750000310,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:3be7a22c2cc01e01a87cf24ce1f528800715787ec1af5833cc1875cb51ef8091"
      ],
      [
        "p",
        "3be7a22c2cc01e01a87cf24ce1f528800715787ec1af5833cc1875cb51ef8091"
      ],
      [
        "a",
        "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "AhgzqdkH9nc/ZJpGQTKs06RwhWHcSgnR3GvNzfPxVF+OLvEEpGkH6KH8jC5aSUp0gmHqy2qsHGRIAeJTh1XZFMnk6ZWbg20E+ROuuOGgm+XXd06Q+NN27QGymZszaFDsBIjllhlYiGyHBR47mJem9wpfN63EjqvNx+I89RScFc65DCQ="
      ],
      [
        "cek_epoch",
        "2"
      ],
      [
        "ltk",
        "AikcucbiqBKmLlWGwyi/YxeudZWALe8tFVbAFi+Lne23Ehn9mt0CLi53e1wdqDj0oqdECw6JDwsRdLm9/ehKKcW/+GFiNvgldcHXre/RKD+/N3dRhmBZG2nT/ryuQCoTUPRo2jisTDINsYVchPPv/5FthZiIJ/YeLEjMNih9GO03DAU="
      ]
    ],
    "content": "",
    "sig": "1633671e42013ab5e84764c3d957722438dcc96371f41a3f5a1ecb6cbde7ef678acb69b8b4aa8ab1de8c8862b49bd257ffcf535d9bd8513e1b4a6c1de7507f60"
  },
  {
    "id": "9cb792f68b0c488e640dffe9de1923c68208f7c9504644ffe344fc1d6bc7556e",
    "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
    "created_at": 1750000300,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:0bf4479ce15352c68eeb581d3dfd2f408778c0397e58d586f7eee7fb46b1ce7a"
      ],
      [
        "p",
        "0bf4479ce15352c68eeb581d3dfd2f408778c0397e58d586f7eee7fb46b1ce7a"
      ],
      [
        "a",
        "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
      ],
      [
        "role",
        "revoked"
      ]
    ],
    "content": "",
    "sig": "737547656b27227f06252201bd609c4ac78d8acc52ce8744251855fcd44c1d295c505f230868a2dc08721bd29cb4a5015ac048a8e7026b8b3fa30366fc8e526b"
  },
  {
    "id": "8419d010871be129aba0cde7cf1785ae8aefc16c0e862c6a92a88f6ca9f081aa",
    "pubkey": "8fc268e623e6386c7f63f8ec19b10cafadcffbd42919513c5a4c7af905551f76",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:8fc268e623e6386c7f63f8ec19b10cafadcffbd42919513c5a4c7af905551f76"
      ],
      [
        "p",
        "8fc268e623e6386c7f63f8ec19b10cafadcffbd42919513c5a4c7af905551f76"
      ],
      [
        "a",
        "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "AmP/kBjnO/MIZAejMPPJJh46D5I2vNSRQRwioJwWgQT2sLSV+oIAKHOBq6g7Cj7sHhz21+aCKQgyFGJhLkUSWiMVwTmKaXSupdjJZ5XjsD45/yw1wnFFcBIp1GIxQeTgklsU+GwmrsYN6cgR9bc7HUutbJxSYsgHGSs8ke25QsDVHhw="
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "",
    "sig": "3f55329925ba1ece938a44e06982e6cb1a9a0a9907c1bc0cab8497ec532a69edb1a0df1fc76875d2a813bf59b1dbfb946bca29be1d58274709a1151b66a89299"
  }
];

export const cardEpoch1A: NostrEvent = {
  "id": "df394111224cfc4f6bf4fd27a43c333baa7e17c5e5d8c07bb2c21b43b4194e51",
  "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
  "created_at": 1750000200,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-001"
    ],
    [
      "a",
      "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ],
    [
      "l",
      "11379374f6cfd052964a16b3b928e552409b12a4e5a8cb37d5fa16f33c0abf1e"
    ],
    [
      "l",
      "90617a95429a7c4f27f71cfeaae691afeffb70ab3ca3156e479073c89133acb9"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "GLM82mPPR8r0l0dffM7BMQYOu9Y4hy+O4At/se/nBnbf+ltL2gQVVsYL41B7zOjVdIzZHeG+g3E9H3OwHZ1a9ed11FXcmZR5l0WCQdPW/pwv4Sbzbye2gwC0WXtrtkOE/6xcoOk6aNjE5X9OxmGGWm32OVTDMwMMV8dEKi4JzazODdIA/GmY8l3lnof0mrF33GSYycJkLSWe+Dr6acZuADIJSg9hVmKVbxmFvqewtuAP440UTRoOZiGT9TLfNBWaNK66qq/bYVykkCul3T4dav5wxfQ=",
  "sig": "a8279e1d3be06918ad2bbc59dc18cbcf7bbf4f1c890e3a1e29b8d62fd2489137c443a3bb5c2bf763a0a80c5e299f04866e774f44e314d9b690697b5827bf22e4"
};

export const cardEpoch1B: NostrEvent = {
  "id": "f869a1cb24e138456226d80105c0e7b98a9c34ba6d3076fc5da69a23ff22d4d9",
  "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
  "created_at": 1750000210,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-002"
    ],
    [
      "a",
      "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
    ],
    [
      "s",
      "inbox"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "UMJcFYbPyCVn8Hsybx/7EvENIZ7eILSW5BzdqKEAoCeP1DEGQazcg4OVBRRF9+OFc7d7qL9vqUI8UWu9eGnXXZ66jaBeX/U6h124ET7bJq+nJoFb6n4SiVsNW4h8xovD1sPjKChyjuFtd+o2PUUPheEsxnyxCnAo3sRH6nY1+x8=",
  "sig": "f46d99540498ddd2560414b5ddc6bf5121ef2500130a99755786884cf1dddaa61efc151f54bd223b2ee000cd8a65b80fbbce16e58b9b3e9a36869917b36410bf"
};

export const cardEpoch2: NostrEvent = {
  "id": "ba469a4110a36b54db22dd4eeb59240d1af15c06ef13a89da42d5627c9b68a03",
  "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
  "created_at": 1750000400,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-003"
    ],
    [
      "a",
      "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p0"
    ],
    [
      "priority",
      "p0"
    ],
    [
      "itype",
      "decision"
    ],
    [
      "l",
      "11379374f6cfd052964a16b3b928e552409b12a4e5a8cb37d5fa16f33c0abf1e"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "2"
    ]
  ],
  "content": "N1pt9uU3cIpwangBUObhkqliosv9EoIsMkVwTdCtRjlyi27fihR6YKqtr9GZMWFH/S3h8q9xpGsAD5HyJcegezIC/+jvxPkBXGyqvEVmGxRxxY6mk0y43uEO/3jB7uo1gFrezTLvoRqvE9sUj34AyNGj0tSHzlwPJgA8FHivAbzHFa0rC/oonJq9RWWt/2QR9zc=",
  "sig": "b02f227c68a334c3160484f23854637c80ed0371b1786280969f803b9a8c232d824b62fe8cf504d1e7228b775d1fd129b02a0880d6860596c203887688b49074"
};

export const cardEpochNobodyHolds: NostrEvent = {
  "id": "bf723fbbd1b7aeeb56bfc1e31848e5d4629d87f1d39562b346baa874e3b1cae1",
  "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
  "created_at": 1750000400,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-004"
    ],
    [
      "a",
      "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p3"
    ],
    [
      "priority",
      "p3"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "9"
    ]
  ],
  "content": "/F1QD0qfwqxiEngvEafjja5nJXJR/0WiwFn3cocV5zjpbRv1W7ah1DEhMFrW8Mzby4crbjgmzi58u4q/azo/NKYwD7IkZWfolPI=",
  "sig": "5d720141086bc1275ac2e8f7572d8d2cb58c824a06878f204f8c3159cb8da77998094ea44a710d9875d8b23b66c2754da9496526f2d2bdb0ebece835fa687396"
};

export const cardSmuggledCleartext: NostrEvent = {
  "id": "a5dde54649f7c763afbbacdcf624a539ce3fc448b602621b4ad37cb5053e0439",
  "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
  "created_at": 1750000500,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-005"
    ],
    [
      "title",
      "SMUGGLED CLEARTEXT TITLE"
    ],
    [
      "a",
      "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ]
  ],
  "content": "SMUGGLED CLEARTEXT BODY",
  "sig": "2d1a56bf4394bb1ed092ed993a7f8d411a56a22a10a2aec50ef074a55458310583e5ed538a7eeadf7f9faf3fb7e1c40b9d5ba72068ab92e76aadb5873adb653b"
};

export const cardGrandfatheredPlaintext: NostrEvent = {
  "id": "1505d86a192236a1baa48b3ecc5cafc8a9cacc5f95b2074a1e9027d8447d7bbe",
  "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
  "created_at": 1749999000,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-006"
    ],
    [
      "title",
      "Legacy plaintext card"
    ],
    [
      "a",
      "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
    ],
    [
      "s",
      "done"
    ],
    [
      "rank",
      "p3"
    ],
    [
      "priority",
      "p3"
    ],
    [
      "itype",
      "task"
    ]
  ],
  "content": "Authored before the board went confidential.",
  "sig": "6031f673b657588f48502a1de2a19209c012a8731cf18a92b3e94b9ae124ed4a11ea873455bd9e4cb6d2d15efdd7eea162694f81aafcf8d86e4f3e54c0973799"
};

export const cardForgedSignature: NostrEvent = {
  "id": "d8bbfa2cc7f6cc7fc533a69d6d33fe2cd88f1a2c77061ab05ad156064996345f",
  "pubkey": "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5",
  "created_at": 1750000200,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-007"
    ],
    [
      "a",
      "30301:d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p0"
    ],
    [
      "priority",
      "p0"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "7ld0oGpyHaluls0xTKieTfIvX1v6syvmwN3tGruSav/2RKCc05kN1kiZxifSWOmigJxv73U0VT1QRj/zhfN3R5zstnkP",
  "sig": "00b6ea8eb2a77a0f618e8ce6650d5079bdd701d181b8cfe3f405e7ec863ae53b71155dc43b2093eadcf45c868dc781742064a15ffaf6471782baf7280192232a"
};

/** Every confidential card in the fixture, in relay-delivery order. */
export const cards: NostrEvent[] = [
  cardEpoch1A,
  cardEpoch1B,
  cardEpoch2,
  cardEpochNobodyHolds,
  cardSmuggledCleartext,
  cardGrandfatheredPlaintext,
  cardForgedSignature,
];

/** The plaintext the Go writer sealed, item for item — what the browser must reproduce. */
export const expectedPlaintext = [
  {
    "id": "conf-001",
    "title": "Ship the confidential board UI",
    "context": "Titles must render for a granted member and fail closed otherwise.",
    "waiting_on": "the relay allowlist",
    "labels": [
      "crypto",
      "board"
    ],
    "epoch": 1
  },
  {
    "id": "conf-002",
    "title": "Rotate the CEK on revoke",
    "context": "Epoch N+1 is wrapped to the remaining members only.",
    "waiting_on": "",
    "labels": [],
    "epoch": 1
  },
  {
    "id": "conf-003",
    "title": "Sealed after the rotation",
    "context": "Only a reader holding epoch 2 can read this one.",
    "waiting_on": "",
    "labels": [
      "crypto"
    ],
    "epoch": 2
  }
] as const;
