// GENERATED by web/board/testdata/genconfidential/main.go — DO NOT EDIT BY HAND.
//
//	go run ./web/board/testdata/genconfidential/main.go > web/board/src/lib/confidential.fixtures.ts
//
// A complete confidential-board scenario produced by the REAL Go writer
// (pkg/sync BuildBoardEvent / BuildRoleGrantEvent / BuildCardEvent, pkg/nip44.Seal,
// and the ChaCha20-Poly1305 content envelope). Because every byte here came out of
// production Go, the browser suite that consumes it is a cross-implementation
// conformance test, not a self-consistency check: if the TypeScript envelope, the
// grant parser, the NIP-44 unwrap or the NIP-01 id/signature derivation drifts from
// Go, these tests go red.
//
// SECRET KEYS BELOW ARE TEST-ONLY, freshly generated by the generator run that
// produced this file. They exist so the browser suite can stand in for a NIP-07
// signer (which is the only thing that ever holds a secret key in production — see
// nip07.ts). Nothing here is production key material, and nothing in
// index.html -> main.ts imports this module, so it is never bundled into dist/.

import type { NostrEvent } from "./nostrevent";

export const BOARD_D = "confboard";
export const BOARD_COORD = "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard";
export const OWNER_PUB = "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22";
export const OWNER_SEC = "3b0257ee5865d8d5b13cdd5d0e742a1ca9252be84d195cf8aab0253856233c7f";
export const MEMBER_PUB = "fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979";
export const MEMBER_SEC = "ab854e64403587d4f4467906db92ac4bbae8e0a135f44f4ac28851fa27974e01";
export const REVOKED_PUB = "3f43c0b5b1ff688a0d64e5f4949038ca4778aa0d4c80ef4704dc8f1d045da623";
export const REVOKED_SEC = "67994271b3338e4981adfd5ed259c090e9edad965539b1d3572d7934d8ad49c9";
export const STRANGER_PUB = "18576fab11d950e658a4b5360e994404460c1d226dae8790ab54ee81a5990a38";
export const STRANGER_SEC = "1219dd21ac2e1a01b90c8a5331f8d2e586dec2d5a28469aa6d691c981988dc5a";
export const LATECOMER_PUB = "e1b29d123fe20bf79e3a129a2c185388dc641efe8c39496d5e263441c22e7409";
export const LATECOMER_SEC = "dc227d373f69c11a3caff345362979221e7582fd7f2e7c2b72bc1ab946d887e5";

/** The board-global cutover (created_at of the first CEK-bearing owner grant). */
export const CUTOVER = 1750000100;

/** The cutover a relay MANUFACTURES by withholding the epoch-1 grants: the
 * rotation instant, 210 seconds later than the truth (ready-daf round 2). */
export const CUTOVER_IF_EPOCH1_WITHHELD = 1750000310;

/** created_at of cardGapPlaintext — strictly between CUTOVER and
 * CUTOVER_IF_EPOCH1_WITHHELD. */
export const GAP_PLAINTEXT_AT = 1750000205;

/** The clear strings cardGapPlaintext carries in its TAGS and CONTENT — what must
 * never reach the DOM. Exported so the assertion cannot drift from the writer. */
export const GAP_PLAINTEXT_TITLE = "GAP CLEARTEXT TITLE";
export const GAP_PLAINTEXT_BODY = "GAP CLEARTEXT BODY";

/** The SEALED title of cardEpoch1AfterRotation — only a holder of the epoch-1 CEK
 * can produce it. */
export const EPOCH1_AFTER_ROTATION_TITLE = "Sealed under epoch 1 after the rotation";

/** Raw epoch keys, exported so envelope-level tests can seal/open without a keyring. */
export const CEK_EPOCH1 = "665d53cc55df584e61224506224f216834382f714e65a78bc9e28ca1fa64058a";
export const CEK_EPOCH2 = "f61120a2dff06e03281f14e5f1c540ebb8f4fd722f044bd8870cd021ea82aff2";
export const LTK = "36c615789d256f5a51f48ce20c8917309540ad15f1a6550a75c2e0122f3ff7b7";

/** ready-470: the epoch-3 CEK carried by BOTH legacyRawWrapGrant and
 * rewrappedHexGrant — the value a re-wrap must leave untouched. */
export const CEK_EPOCH3 = "c01c27d8bf1d2c47f920585de51e48192de4ae4b84f0307ae3d7e640487a0b18";

export const boardEvent: NostrEvent = {
  "id": "2de9b41dcdf06a79ec04611c28d13dcce708a7d9bb9fcb5dc9249e7c261294c8",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000000,
  "kind": 30301,
  "tags": [
    [
      "d",
      "confboard"
    ],
    [
      "title",
      "Confidential Board"
    ]
  ],
  "content": "",
  "sig": "67ea1f78c156fab3270867a1e40c1715e14d531619406f18c050a566fcdbc8932032408d6fb5b1954d1a629b0bfc496ca5be5650318b7b9b7da11812c2569981"
};

export const grants: NostrEvent[] = [
  {
    "id": "78eeca87f93fcdd01e5a44c0f656659e6d8f0c924d97ed4f455da68cc601d7d0",
    "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:e1"
      ],
      [
        "p",
        "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22"
      ],
      [
        "a",
        "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AlZdzgl/7VBv1sUBrhT++qc3LuVpS/XBP6Kx99IEpIn7CMUA8PPiubCbboLjYyxx3sp9zv0ybgQkZLHtK06oeReoDq6TkvswlMNr+RJCzkiEQlfhZqrX1wZ0Xn5ZNVhgioeLIp+F9R3aFker3BhC3ACBjoCq9ciFZfz4P02r7JRA1tI="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "AmPuWpInR7trtvo6pRs7mleov5H88vKmSMrBgM6BzJdNVTknaPgKkDcchsTPl2BfAWvTxZmOU1hfXVwoaHmm2YDveAUR+H9DRrSfpt4BVHMj0UmYajNQFuRjU85TFw/aAuoWgvdvD6xwq6IPOvQzHkaWo1PTjOOgOzqWg19RCKhodNE="
      ]
    ],
    "content": "",
    "sig": "f448c570ba801c53dc71dc3f1dc797bb29000be4a9fb2d04a8c0acce278d4dc2daf7fb375b89dcb7c402cca411802417e33f08bf9f32851d23af811b0d5f11bb"
  },
  {
    "id": "015b67d8a7d2473c97f6847e9e4315729ac8788607366f0ae3cf335867857eb8",
    "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979:e1"
      ],
      [
        "p",
        "fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979"
      ],
      [
        "a",
        "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "AjaKd5jEmXfPBMeOCmsBdW6cCud3RvFDFKbAx9fybfOGBFXIBlOV3e1oRibLrF3jqdk2OnuSqz+caui+QqzL/zyvmKRQ7i2Dk33JiKYXX1BJ6ZfEVqLcfZBSvMKpG6dsXETGFxvI5gUNC0KG+h2Cb4gADLrvFQ6cuDyKE3+XsvzcWJM="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "ArEWs/oCDdvn8/fXBJX9XaCvGMKtidt040mp9dJV3/aXKv7jOJBNVlAIPAH6kzCu7ELYaH4hDrLI/bhSWJVi8poeaNculdpoIkERNwylV7pHQ2M9Nmx9d7bsdENWQHfV60LoM9vKdWFxBaissI4Owjsopj53AsoVDGSjm2yRun/x+84="
      ]
    ],
    "content": "",
    "sig": "a9536dda0a7623282c61d4c8de7c618eae4743e6d90bfd8a6b03b806904781ae6bf675a7307a686645ac817fc01368f756fed47d6946aee5d08f9e481448ee87"
  },
  {
    "id": "61454e27a3038d691629f5f01d0b54ec2e808580d80c5e1bb51db66b9f867c4c",
    "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:3f43c0b5b1ff688a0d64e5f4949038ca4778aa0d4c80ef4704dc8f1d045da623:e1"
      ],
      [
        "p",
        "3f43c0b5b1ff688a0d64e5f4949038ca4778aa0d4c80ef4704dc8f1d045da623"
      ],
      [
        "a",
        "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "Ak4qEvjogCVsCf5Wt5W3GdnfsRtzx1UZY0Th5AAdYxrYuUfT6nueqjmZsTBFZtyEBR9kx/F8mrOy/UNfbYVmkbbdc8m8p9415iM7ejcTf95iky6mDuYaSvYvNTRK2kHM+d3E8oN0SREUHP+r9BdINhjk/Tl/LUQfohuZ+K0m2cd7nVs="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "AjMLd/be+52uJoEIVzUvmi+lxl5wnOpJUL555wrXrBnKYgY1mJnTs83sGWZzxC9XcZqJRIax1ZSW+dVYfn6W5DodMedl3OFDwj5guSCoddNsHMDDh2ZoR86wyhY2sgIYHSrT4q91UAV5FNabf7tp0iMTwtYu3CM5SWUiqR1cCVZ811I="
      ]
    ],
    "content": "",
    "sig": "e90648d03d92f04de8075425c3e8351ea506c91d3742cafb92870b2410de02ea22ec56b537eb520c03516b9d80f7ab459366bc9c2207dd84d26e5ebf480d835c"
  },
  {
    "id": "9456056733b0eae1f6f129de88e16f0af78a641026e5a89ec2c6d58ee28df0bd",
    "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
    "created_at": 1750000310,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:e2"
      ],
      [
        "p",
        "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22"
      ],
      [
        "a",
        "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "ArusUz7F1BnEaXHEqBrSu3ziSRV/skrPk0681jxFfGq0aC3qXctkWMNBDeqgU3RwKRp8FFsAWRj52iDtfDFZCAfLvvP3mux2cJ/Snb9BLUiHexz18xJFOyOZ8RqARbNFZgix/pS9F1aVf3nnOTK8RLyeA673/uJiXzUCRZZI8/exbpI="
      ],
      [
        "cek_epoch",
        "2"
      ],
      [
        "ltk",
        "Ap59vfFwoGHIbJ4tKC1iXTsbH3c9UxoQ9E94Xs/SNzCYgAw8/xzhdCZ2KRYKMwRB2hhV6IBHrv5J/Jeue1C8xvm4EhpIgBB85TIdA6Aq3IK4WT8cORxVwwCo2N8yDwjPjTdKUtfgws9QvW1X3krT07cLVFvV6fgwTxjPuWRc992xmU4="
      ]
    ],
    "content": "",
    "sig": "6a39f2f981d852d78f76d0078ca3917f6c95650745080aeb730254015c2dcae10c7ba8d21323fc13be9766badb4f0c0622daac09a383e41494ccdf08194081e6"
  },
  {
    "id": "c8df6407025bc723af8a65d72b3f25d4dcc44c0e420a1c10f5fa3e7ce5a46843",
    "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
    "created_at": 1750000310,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979:e2"
      ],
      [
        "p",
        "fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979"
      ],
      [
        "a",
        "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "ApStXqRGXfXEj3Lje0fFwtZpfAGc7gd4dhiObdJ9YjG2h6AO6045pAW3XuJ8gWauCoQBDg90oeP2Qy0x0jURaw9uPFteCiWCUfM8BkTlRzgBnP/LweBcycA1DtE5fOgsOJ1vmwWbL8xbLhBdxOTwyqqcpQf8YT9ecaEDQ/eVbQIXj9I="
      ],
      [
        "cek_epoch",
        "2"
      ],
      [
        "ltk",
        "Aho9ungSz1a8xRQKfz4xg13ksV8onPNTSjzCsh9Voc+AcZucw+PFomPp27lvM75gCrPNP/sddWRYWDaFsLc1YckzsK4Gwr2j0xeubZ3x97lLQAgyEiWy7YYXUxde0tS2QbIHiwCBnfTCW2jjNoyVeBgbP0fN+R9Uuknz/XxtbVfSy/k="
      ]
    ],
    "content": "",
    "sig": "8992582349e47e405ac81e2ba2bb578b24c3b46adb7c6c8d11e95a08fe27e961d3ac96b81e2452f344ea8a271b02d4f7690ae249bec084b2e35f52df6e5ae170"
  },
  {
    "id": "c66e9af03b6ea73fb2a289a611244f99848bcb00a527be74deb4ad925f3e0948",
    "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
    "created_at": 1750000300,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:3f43c0b5b1ff688a0d64e5f4949038ca4778aa0d4c80ef4704dc8f1d045da623"
      ],
      [
        "p",
        "3f43c0b5b1ff688a0d64e5f4949038ca4778aa0d4c80ef4704dc8f1d045da623"
      ],
      [
        "a",
        "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
      ],
      [
        "role",
        "revoked"
      ]
    ],
    "content": "",
    "sig": "99c3277e5115628b108fe9e8c7d259297cb30dcec877e8cbe8c9dedead72c9a48cceeb20a6a1634124ecca966a11bf1dff9e75fd08343b51c17705c6543ae09f"
  },
  {
    "id": "2cf06c00b30f501a9e01b6730d78d69600de501422e954f5dc85b15e76537a21",
    "pubkey": "18576fab11d950e658a4b5360e994404460c1d226dae8790ab54ee81a5990a38",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:18576fab11d950e658a4b5360e994404460c1d226dae8790ab54ee81a5990a38:e1"
      ],
      [
        "p",
        "18576fab11d950e658a4b5360e994404460c1d226dae8790ab54ee81a5990a38"
      ],
      [
        "a",
        "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "AhQy7+GNxki2oTS9Ogqfo6n7nOlK9PBOWrD5TO8LCzeHHrTR/z/8jskELHQ96MU0oRP3NFYs2+rHlNBys90RXso3EMRYngA/TLseWcoIu5leGXbS1BD1AaATQw1DCMKOs+rimaz3FxTqAVrQD8VIDqiZQx9XzPHfwnz0N27Q4yoSkJ8="
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "",
    "sig": "4e7db25dcfbb4e6ba4111a5c72860abecccaef55883cff491001a611ab7edc640ba4df17ac8bd4451b619f8f74105acfc2f43ae88e045a615ab0300ab31dae1b"
  }
];

export const cardEpoch1A: NostrEvent = {
  "id": "792a80f51d911a6707d5852b28e4d8ad98012a4123327f550ef4b31e547d9703",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000200,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-001"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ],
    [
      "l",
      "554b29a5d1b7c7dc4c12c44a0c274cf70aaf9100636f521d7aa956de946e70bd"
    ],
    [
      "l",
      "66b7ba386796a2ec31f85ddb47835a6c927be11eb534bcb6b6a939c2a50c0c5c"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "KTPhTFWZxjATrOFSxkiFGp8bKvTM36mCiPZIMP0Ovr1dGJdPsDLJpIWW1hA2Zl8BBU1wTnEAZge5CDHyV5fxw48jFIShCg2KzoqVWya8FrFx481tMyxeMEnrfMQK3gz3347/yUhfq1GI7y6yqgICUrSZ++y/hDLSMcAN9GhqrPmzHRbW67b7VhpukofwK/SOcYg4B1jRu28Qlam/2gHppxjIATKGXHi3zrs4QCxHQEy3CNmO7fIEornebd8yzfag5HFHjS1BpxGGv4bSvGo9t0WMcG0=",
  "sig": "b2eba8ef0ab030518eaa22d9b0b5b75139a51a7b04eb3aaa880d5e3e2bae48773d8054aa8ab5827918b0a4fd88f13b470ddff81806683707663685892f4a30e4"
};

export const cardEpoch1B: NostrEvent = {
  "id": "56c7c688c76bdab2d01613dc8781b55e78fe6ec905b6222a2e35e0eef315dd7a",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000210,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-002"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "inbox"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "qV00rR4Ki2pc65oirFAq4w7jM5H8c7f0OnwY/ojgkiZcWQXvPK0B0/SUHOaen934ZzaLTlpoTULFR/lrjP2AyXU6hLJ/RTkSbTpKYImw8gCS9THNYKGaFn8oSUDlNke/hPtj8T34HrAMuGD3B/sBG9Ra9sfYrk6lgVpCYX/9zGQ=",
  "sig": "3596778e635006acbd6eefa0abfed35d4c6801c8a9ef8e27770d88186d51e530f0dc0e60768dcd4fe2a1351b638ed3d562a835c7c99167bf93e412dc6aa2b632"
};

export const cardEpoch2: NostrEvent = {
  "id": "ab5742cc6de7a2ba64eaddf54c59f9575b0f63f5d2ad8234e7ad4452dba3a9e3",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000400,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-003"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p0"
    ],
    [
      "priority",
      "p0"
    ],
    [
      "itype",
      "decision"
    ],
    [
      "l",
      "554b29a5d1b7c7dc4c12c44a0c274cf70aaf9100636f521d7aa956de946e70bd"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "2"
    ]
  ],
  "content": "YXTfpJ+CtmO7ewFsXSZNdPr4sxw6F2KFp8BLKBhUsh0pm461nmZpVSons85vYP96aZtCMQr0ZM+J8zigwNdDOvTqo/RIcT9h7JzjlOlan/CdGMkfvDQyfpSPtW1sI/8+Nvxp0LI1O9ohgbNcZ+m0qvdUE/CZ15wTp9PT9mfJbc82RhX7TmHyjjqm2eMtL4rU2C8=",
  "sig": "2f319b33086569fd4b8267862e725043044deba527cf4f8c6db5b300e8f2920c8d8bb81a046fcbb30b8644392a0d48b1722540be50b695ad8fdede7246c60664"
};

export const cardEpochNobodyHolds: NostrEvent = {
  "id": "e19fabdcdb463a850fbc4f41e51f376ac8820b788a62aea2caa96d02b68d1166",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000400,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-004"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p3"
    ],
    [
      "priority",
      "p3"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "9"
    ]
  ],
  "content": "8YGcvoBOZ1Y4EijAtZtfzqp8vqi7BWs2fwbxRmCsEGzB2lejjBnRBvidwSckVHAWdYr7hCbMczaHAH7TpSHQNVI0Amv+caeNc7M=",
  "sig": "0052b213e64dc5bfea418cc201559b587649f2a6ec55367d5ed92adc2757b0785d4c5215a60f029656cd8df9ae1d22d8ef9e9091eac53d6b846361cb83c8b3b1"
};

export const cardSmuggledCleartext: NostrEvent = {
  "id": "b6399e2861b2b73b1f2a0f4241ca998dda546871bb497c48b0d8bf23c3bf3ed6",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000500,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-005"
    ],
    [
      "title",
      "SMUGGLED CLEARTEXT TITLE"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ]
  ],
  "content": "SMUGGLED CLEARTEXT BODY",
  "sig": "de043c39d3893369fd895ad5777c75832cf1a4f79d9a77f09ac31b5eb6659ca5c818e8ec528246c8e8783e2ed3fd425ec5a44f0f5b7ca284479c7e4bc466e1fc"
};

export const cardGrandfatheredPlaintext: NostrEvent = {
  "id": "f101ca7160c7b2cd8f35725d92624404ead7d7a45532cbafed1e4c758b455076",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1749999000,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-006"
    ],
    [
      "title",
      "Legacy plaintext card"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "done"
    ],
    [
      "rank",
      "p3"
    ],
    [
      "priority",
      "p3"
    ],
    [
      "itype",
      "task"
    ]
  ],
  "content": "Authored before the board went confidential.",
  "sig": "ba9aadcd3fdcbaa20fa78c8ef26a9947410656c3e276ce81fe2ffaa76feae44c52ec51b0e0e400ddd6077fd01c789c311306eeb41774782836af628081fc5d5b"
};

export const cardForgedSignature: NostrEvent = {
  "id": "6e99cd0c653d1f8398699766163841ce710318286ffc535152a61cb20ebed98e",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000200,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-007"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p0"
    ],
    [
      "priority",
      "p0"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "QLeVqoPfvxiOs6j2wCh3JFds6SKBCodrBaDQNuZUOv4gikhzxr1bY3mAo1JYCs5T9RijI2+UBYsFHCHxkTJahpZd9eEf",
  "sig": "009774a2f64568a2983b09677c6d6175ce3b7b853de0cddcb9b5993a876673058e26a368f47c62caeb2509a0f49628307b28c47487adaf55dee2b167e4ea4ba4"
};

export const cardSealedNonObject: NostrEvent = {
  "id": "8c46e4f50c3d5ce92c0f4222dc08870eb203526fda9104d54d171e4c6604c123",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000220,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-008"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "No6PiVwfVgjerKIWibUW5yh5NqhIiM9M7w2G7ispydwZOa+gZodoFx9pr7r6z1WETw==",
  "sig": "82cfdd107fec431d9d5be7cfda65d7a032dc12714833c2551770b704a9632849d342bc95ef121e87bf7a7f851d73e44a5ea3d22989c8e8f7990421689116eb4f"
};

export const cardSealedNoTitle: NostrEvent = {
  "id": "05907b5532f51001f8bd9ad4efad341823329af5b4495d7b7099a84223b938d0",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000230,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-009"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "OZSfVd9t23fzb+TDjqU7PNh43qugCS8ipHHi+3WlozkFN+nAjd59sOZpxatgpznGWW3QonvLc97ph0TrJGenlbx/NRmyStnh4GodOaSo",
  "sig": "d53b1d11307483b1b589cbd883c0400e7df3f16e16d4885f37f8c32f64dacdceb975dee9a85e61639e881c85a3c570e27926126ef2b75a024c9ddef0e0fa151a"
};

/** ready-daf round 2: the owner CEK grant for epoch 1 signed AFTER the rotation.
 * NOT part of `grants` — served alone, it establishes a cutover far later than the
 * truth while leaving the epoch set covered from 1. */
export const grantEpoch1Late: NostrEvent = {
  "id": "fe48a08b255e84fa32767b387dc2efde4b9ac62d5a30b66daf04942f158bb097",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000600,
  "kind": 39301,
  "tags": [
    [
      "d",
      "confboard:e1b29d123fe20bf79e3a129a2c185388dc641efe8c39496d5e263441c22e7409:e1"
    ],
    [
      "p",
      "e1b29d123fe20bf79e3a129a2c185388dc641efe8c39496d5e263441c22e7409"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "role",
      "contributor"
    ],
    [
      "cek",
      "AiSDJO8IIjz489D1IVG+1U7nCYZiWDOZwFbTB6hwOpB7P2Kidvq0KPHlANfQN3LEiZc9Ivs+qlSGIR1BT5AbNDmw9ZaQk4ynRrLBPoEnBqwQF5aQEqKW0SVt/6zjjJ/51YtjLxlmJWa/zVbZCnK4Ulw24IqzDGyTKsvItSh+chAq+oA="
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "",
  "sig": "1dea73398a3004f7d2cd8e410abf0f3f3a47d94c8fd27b22036bcc8310ba6354f4945b479fd6a53f5fe17625fd716d91c4a3950db1b4b63c1ad9c61ee3a90707"
};

/** ready-daf round 2: owner-signed PLAINTEXT authored between the true cutover
 * and the rotation. Post-cutover cleartext that a manufactured late cutover
 * grandfathers in. NOT part of `cards`. */
export const cardGapPlaintext: NostrEvent = {
  "id": "3a732be8a612b0fe4fb83ac69e642393480d2ecfc407736fc19a50840bc0f4d9",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000205,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-010"
    ],
    [
      "title",
      "GAP CLEARTEXT TITLE"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ]
  ],
  "content": "GAP CLEARTEXT BODY",
  "sig": "b3fdb967ba36697c8eb30ce77f613a9fd2eedb7ffd4866bc6b2a1aefa99b4391a32a7753e8723c9dbd9a2e9fe7edb9d542df1c302c2960bbedf7648f33fcd971"
};

/** ready-daf round 2: sealed under epoch 1, published after the rotation. Its
 * epoch is the only thing about it that witnesses a withheld grant. NOT part of
 * `cards`. */
export const cardEpoch1AfterRotation: NostrEvent = {
  "id": "d8bd87a458b104e957665bdef01f17db83184263ad6ecdf88bd141870920826a",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000700,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-011"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "7eTuD9BE61WKIvQOfXNrRyC1krjSECXWmsW0eK3jT7QkqU2k6TNChmnauoo/XGGBYEtqg/c1bJr0VnnnUakcZOglsNm2z9cnUtlpXpX7PRx8YD9M8n67V249Ds1CjEvHFzIJ0BhHC5VoPZ1UR/iPHynfbwT85NLlcCkG1DaBqOG/lXuf6vWGj6j80g==",
  "sig": "d240801a8a703eae75937e0ff7553f195c76dc059367dc5ce9f9acdcd1b8d992793c7aea128fa5c96753f7955c63f1a300b5f849a33d9e73d64e7accff6ec0bf"
};

/** ready-470: an epoch-3 grant to MEMBER whose CEK is sealed as 32 RAW bytes,
 * the way WrapKey did before ready-c4b. rd reads it; a NIP-07 browser signer
 * returns a string and the bytes do not survive the UTF-8 decode, so the key is
 * silently destroyed. NOT part of `grants`. */
export const legacyRawWrapGrant: NostrEvent = {
  "id": "3bfabd933d89b38d400c960f185c9c13ce2f7964e8df9129498777f5042d7b08",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000800,
  "kind": 39301,
  "tags": [
    [
      "d",
      "confboard:fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979:e3"
    ],
    [
      "p",
      "fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "role",
      "contributor"
    ],
    [
      "cek",
      "AsU0qw/4KmJPQvJaDkoV75O2tR8Z1dBGj4sveDF7/xyB/E+LDV7tC38N/p8bSBjbZ3Oueb+4bKVbd3oHI4Dy4qkKM0mawVMCFjgi7lnwX11QWdVwPVdzWAgm7kekdW920eDO"
    ],
    [
      "cek_epoch",
      "3"
    ]
  ],
  "content": "",
  "sig": "4e146d1b85f65a954f121b358311ad266809b0edf2b1d11ff3c17cb0149a5d58b848d9adb1e96136560499c604b8b76de8920565f5e6cdf53d23325bf74b558f"
};

/** ready-470: what `rd confidential rewrap` publishes over legacyRawWrapGrant —
 * the SAME CEK_EPOCH3 value, the same epoch, the same addressable `d` slot, one
 * second later, sealed as 64 hex characters. NOT part of `grants`. */
export const rewrappedHexGrant: NostrEvent = {
  "id": "158bdcff3d81c1613c18ea8c85fd36e5d9532c396f4acb22ec1d0dfa4cc032b0",
  "pubkey": "40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22",
  "created_at": 1750000801,
  "kind": 39301,
  "tags": [
    [
      "d",
      "confboard:fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979:e3"
    ],
    [
      "p",
      "fe6d1c1be590d0247095e672d8cb88cbf3dfa09c5d7115291f1070a9c9ef5979"
    ],
    [
      "a",
      "30301:40e07b865ddacd26b1fc3a41bc2abbe0f15be93a789276b606666795fb6c2c22:confboard"
    ],
    [
      "role",
      "contributor"
    ],
    [
      "cek",
      "AnYoQv5AitDkQx9KHZ/V5VaQKfJGNhAXiBfehMK61CZvFcTwcnqWvhiLSpZmNzp1w62jc0Vt7bUeTs1JDJALN1w/z3s2JrpWo72qD47WXqGu10BcrDlqXTSpf1QyL/sA9f2HWxfBgMtXu8NA/DwCoZWib3CGh5G2z/5Fmm2pySpSzMM="
    ],
    [
      "cek_epoch",
      "3"
    ]
  ],
  "content": "",
  "sig": "604927aeef252e336c1435c24c7de9930e1c0eef7b8da1e9b4b0aedf6b2da58475e0536b5c78861b1e0e1be9420053c9417163ada1ffb9d0ee1b76f74032027b"
};

/** Every confidential card in the fixture, in relay-delivery order. */
export const cards: NostrEvent[] = [
  cardEpoch1A,
  cardEpoch1B,
  cardEpoch2,
  cardEpochNobodyHolds,
  cardSmuggledCleartext,
  cardGrandfatheredPlaintext,
  cardForgedSignature,
  cardSealedNonObject,
  cardSealedNoTitle,
];

/** The plaintext the Go writer sealed, item for item — what the browser must reproduce. */
export const expectedPlaintext = [
  {
    "id": "conf-001",
    "title": "Ship the confidential board UI",
    "context": "Titles must render for a granted member and fail closed otherwise.",
    "waiting_on": "the relay allowlist",
    "labels": [
      "crypto",
      "board"
    ],
    "epoch": 1
  },
  {
    "id": "conf-002",
    "title": "Rotate the CEK on revoke",
    "context": "Epoch N+1 is wrapped to the remaining members only.",
    "waiting_on": "",
    "labels": [],
    "epoch": 1
  },
  {
    "id": "conf-003",
    "title": "Sealed after the rotation",
    "context": "Only a reader holding epoch 2 can read this one.",
    "waiting_on": "",
    "labels": [
      "crypto"
    ],
    "epoch": 2
  }
] as const;
