// GENERATED by web/board/testdata/genconfidential/main.go — DO NOT EDIT BY HAND.
//
//	go run ./web/board/testdata/genconfidential/main.go > web/board/src/lib/confidential.fixtures.ts
//
// A complete confidential-board scenario produced by the REAL Go writer
// (pkg/sync BuildBoardEvent / BuildRoleGrantEvent / BuildCardEvent, pkg/nip44.Seal,
// and the ChaCha20-Poly1305 content envelope). Because every byte here came out of
// production Go, the browser suite that consumes it is a cross-implementation
// conformance test, not a self-consistency check: if the TypeScript envelope, the
// grant parser, the NIP-44 unwrap or the NIP-01 id/signature derivation drifts from
// Go, these tests go red.
//
// SECRET KEYS BELOW ARE TEST-ONLY, freshly generated by the generator run that
// produced this file. They exist so the browser suite can stand in for a NIP-07
// signer (which is the only thing that ever holds a secret key in production — see
// nip07.ts). Nothing here is production key material, and nothing in
// index.html -> main.ts imports this module, so it is never bundled into dist/.

import type { NostrEvent } from "./nostrevent";

export const BOARD_D = "confboard";
export const BOARD_COORD = "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard";
export const OWNER_PUB = "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523";
export const OWNER_SEC = "bb489575136886d0c54d19d7a1bd24cecd1fcea8d18943189cc57f30f06d2ff2";
export const MEMBER_PUB = "9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68";
export const MEMBER_SEC = "ac5bebaf7b5bccf690cb1b78422d66eddfd7dc7d4448d7cf11547535a554a26f";
export const REVOKED_PUB = "73700987425c23a9b2922983621ffb16bd4a00e603ced2e790c3661d41a594c5";
export const REVOKED_SEC = "744bb78a67ddc2406fd735d389b2f1500737bf425d613ef8b526dda5249a9505";
export const STRANGER_PUB = "f6e0f5ae30d4cf5cfa7a68b75940412df98885bea580a211dc643c3329cbdcd0";
export const STRANGER_SEC = "c164422191a09c502a533da9d0bec06375dcf6b6800025450b80b3bb623c8dd8";
export const LATECOMER_PUB = "a97a43be2137eb35bd85b85ce1ce3ceb674c8dab32c5cb3575d4bec34b310af6";
export const LATECOMER_SEC = "443be536655e00935950a9935c75f3f29befe92e66b5b75ed3b570f6603bd2f0";

/** The board-global cutover (created_at of the first CEK-bearing owner grant). */
export const CUTOVER = 1750000100;

/** The cutover a relay MANUFACTURES by withholding the epoch-1 grants: the
 * rotation instant, 210 seconds later than the truth (ready-daf round 2). */
export const CUTOVER_IF_EPOCH1_WITHHELD = 1750000310;

/** created_at of cardGapPlaintext — strictly between CUTOVER and
 * CUTOVER_IF_EPOCH1_WITHHELD. */
export const GAP_PLAINTEXT_AT = 1750000205;

/** The clear strings cardGapPlaintext carries in its TAGS and CONTENT — what must
 * never reach the DOM. Exported so the assertion cannot drift from the writer. */
export const GAP_PLAINTEXT_TITLE = "GAP CLEARTEXT TITLE";
export const GAP_PLAINTEXT_BODY = "GAP CLEARTEXT BODY";

/** The SEALED title of cardEpoch1AfterRotation — only a holder of the epoch-1 CEK
 * can produce it. */
export const EPOCH1_AFTER_ROTATION_TITLE = "Sealed under epoch 1 after the rotation";

/** Raw epoch keys, exported so envelope-level tests can seal/open without a keyring. */
export const CEK_EPOCH1 = "49b4c4d84488f8843cd767d4658df0b83a720512f64cadfa304acd424dd52777";
export const CEK_EPOCH2 = "62fad41f817ec4cb7a87848af1e6d6bf48beaa104e2ec13114daf8ebe193cbaf";
export const LTK = "0e8c3649bd483f48b8993f2b362fc28bb0bd29edbf24952065284d4b69268735";

/** ready-470: the epoch-3 CEK carried by BOTH legacyRawWrapGrant and
 * rewrappedHexGrant — the value a re-wrap must leave untouched. */
export const CEK_EPOCH3 = "e6a356d12d8b5f96c7a0f4fae286e611e2219108813002559ad6f19a3c419b46";

/** ready-470: the sealed title and context of cardSealedUnderEpoch3 — the text a
 * person sees on the board page once, and only once, the epoch-3 wrap is
 * browser-readable. */
export const EPOCH3_CARD_ID = "conf-012";
export const EPOCH3_CARD_TITLE = "Sealed under the re-wrapped epoch";
export const EPOCH3_CARD_CONTEXT = "Readable only by a member whose epoch-3 wrap survived the extension.";

export const boardEvent: NostrEvent = {
  "id": "8517d1e3b752a3ee72c53db4b4aa20ab767a43cb15fc1341806711ba53f050a4",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000000,
  "kind": 30301,
  "tags": [
    [
      "d",
      "confboard"
    ],
    [
      "title",
      "Confidential Board"
    ]
  ],
  "content": "",
  "sig": "ec6434f3371e05c15227fa457b57602cc19991fce6da3801d38ed8b8c042138b3a7f64170f3d4faa8f11f13511bb859ae97322203bfe1f3a1c2338da5601caa2"
};

export const grants: NostrEvent[] = [
  {
    "id": "ad1965800b3d71b768a2173c3f48f07baf9407dc861b47e74282b9e5e2730ff2",
    "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:e1"
      ],
      [
        "p",
        "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523"
      ],
      [
        "a",
        "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AhMN5LpRgLLrzAW2gNJME7DENvQJqk1dOwYUed+5jWMsVKoi4YvCydXv+bxgIOnYWk210Bd+oWh6HMbSkxOtBPT2HlVj5D5Gnl04lqAoJtcxAoo6TB2rNIMMn1lqMLzWqrL7BVyreEE3oc3NI9HqyAPheNHlCLwOQk0LFaJiuP5LRZU="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "Ai+QFlSXA/YdEQkCNDD4vorHs2kTVqfINnntnX2iBtdyF8LP0nkoSQxyQuW07T07shFitNzvsm0qsaP7gKYl+Uqc2lrepQZF9fm0fL6gR9YW5fs0Itlnyx2ZXCOE/ntyBnmkhjBHHtDoQLoOqoTWB0OL1lhgLWeMBxgp0l3K3ZWzfCg="
      ]
    ],
    "content": "",
    "sig": "97d8d6d8dae99fa86781fd348ead650fd0f4241ed8d27fa2cc379d85a692b10ba479130bd8aa696a45a22bcb494096a7fd564c8dd3bcae19e627dbe81457759a"
  },
  {
    "id": "fc4594f0329cdfa6c3049c163a1c8ff4353d54936b4b1bf840c931bb8b3b3265",
    "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68:e1"
      ],
      [
        "p",
        "9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68"
      ],
      [
        "a",
        "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "Ao0NwjOZD+5wbWU3NTgULKYmimdGXNW3crZX4I6y9LhIoGy/jgcyh5T2u3wABl5DxW/Tyigk4MJXgo1dik5H1DWWmPXvgrzWvRtHItL7Nm8ZrnxhhJvN/g5TCU83sGpoGODs2vLlB0XX5mZW2gQLMSDqTWG3LQUgqTB61T5OPpF3gjU="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "ApFdpeSx4CsAE777fJss8/R4yi9ifA0xrOTC/BMbLm6jazGCniu3UP3F61/n2iIyAoPxcIjGeWTk5WyBOuO7AsISctQRcjqWlUvXe09JMD3TMJh2HhHP8cTlgTiBE0TuaIn12e61emNJydeNNXJhhks1lUguuWWmtjE4v+vM+KHRpqc="
      ]
    ],
    "content": "",
    "sig": "53b1ed3c33976ff8f17a183efc5230fd6a798b6f6770fae0186381be48f63233a49d1abf7ab6e31dc7523e02238b64d72010cb9d43ccddf626b3c217540e206c"
  },
  {
    "id": "2d09cafea4f7c6ea4fa447d9b3e3cdb97e05cb92b78be531ef09e5981eec000a",
    "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:73700987425c23a9b2922983621ffb16bd4a00e603ced2e790c3661d41a594c5:e1"
      ],
      [
        "p",
        "73700987425c23a9b2922983621ffb16bd4a00e603ced2e790c3661d41a594c5"
      ],
      [
        "a",
        "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "AqhVQyXCjSFaVCLwOj3jSPOdhiln8JD3x4Er5dDbLdKAqXVXqxzPHktIrXaSE2mCpMIGtLVuoPGGtBFjebq4cJ3+LRsdz1HwXq6ESspxoGvBMPQAzQTitFEvAfiNE5hh/Md97mTqwJ8d0okiMVRgN2wk/+N3u4LGSwkH3wkkZPuv90A="
      ],
      [
        "cek_epoch",
        "1"
      ],
      [
        "ltk",
        "AteNY5rRCg6cTxURP4A5pNS9qv/PoIYl8KDqZq6Ql86PopYtb/1YqEPEz6puI3/yxuDui7876Em40jSqqw+reX3VvR7hR1EFQJukFVQElTmquNYnZb/BOrUMGTT5UZBXAOMYdYgdWvAG//6hpzlWdN/DA6woZ0IbDV4e0eiefv68jEk="
      ]
    ],
    "content": "",
    "sig": "1a0f7a3f7ba08b0f75fd549bc01114f212adff649ac15f3c720b65e681f96bd3f3e469427b5bdb19f2ba72cc241fec281df7a3ddbdcb80eba9f617f74b12f730"
  },
  {
    "id": "282ca1403369c8cb8323e02f2f9b3c0c1761fa83cac749b57af031181357747a",
    "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
    "created_at": 1750000310,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:e2"
      ],
      [
        "p",
        "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523"
      ],
      [
        "a",
        "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AonyrjdlAGvGS+Wfm/GUM39j0IdDMRfmT0xdS3rbxq+zbNFZ6aZlzsvHCXPxiE4sFjcE+nhrkw4fA0Ri8bekAyy3Mhjz2Cb+q/CalQ8SNwDhCWn4XTrqzEGFd1LtdKb5csoCWr+IhjcjUFVOoy2zPzGAFnBLoR3FZDgdfhzX2OZHWdA="
      ],
      [
        "cek_epoch",
        "2"
      ],
      [
        "ltk",
        "AoPz/6C0qeWuomJKlP6yll6jBQd8eq9oUJEjE6wG0OsyRZ9j1e79KQFc+zU2asJM42g3iw4+mv5KIKwlcLkMvb3MqKexG6r2Y+hfNJQSRSmF71Euc33oBKLN1qsjTYsqqsm8tonJTiYYmLh3/UXTsVCGXyCtzwqjBKbRxjALj3n63Dg="
      ]
    ],
    "content": "",
    "sig": "785e1fc5f4d8e595cb1e8a427ad1cdc7712641b602642441989bb39df11e39b9c9265325f132b6f58ffa53b4645fbae210cdaab3b2dcd6291f826b1371dc38c7"
  },
  {
    "id": "fa50e18bcd851971e6d20c04190fba8cfebe64916b8795e1075cdedc2c8873f7",
    "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
    "created_at": 1750000310,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68:e2"
      ],
      [
        "p",
        "9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68"
      ],
      [
        "a",
        "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "Ao26vWF/VMpMgsOlpmAoNHkbZC3ufzO7WmCKeVLpoSK8OjOgBQnVCrkRWCFiKnrHvNS+21X1M6+rZhpg0MrVd2PjFXAPusmtUHeiNWb8qFhZN4WCIfxqxsrb2zbgWaiNhns5XEagP0NqsGgxvBOgIh6QOne6Z3moQLCcLV52/d8JL0Y="
      ],
      [
        "cek_epoch",
        "2"
      ],
      [
        "ltk",
        "AnXrIxLmeIDnNIQP9JUrB9VOyEot7eMsuDPkBpND2cVGckWfkI9r7NNoRHfKoqrYHZr6No3G+OLXOwaDgexAuBAHEFsyQztZxt9sOzVI+T+ntvApYE/MiummzWoZjR2JK0F2xqu1vX5bYybhrrj+VSqD8qPJA263GTYVlwDaL0dcKxY="
      ]
    ],
    "content": "",
    "sig": "98dc6eff46be499b52e2c49f040c59d5d2505ec9939a80eb0803542494929b9b55ea9eb1805838fc86d6bb0d9d3cbdcae3f1cf99996cb2681f0af46b3405480f"
  },
  {
    "id": "edaa44fee66a8a81f1e615986346e7932b6b2d08b8c4a34e57ea9829033ecef5",
    "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
    "created_at": 1750000300,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:73700987425c23a9b2922983621ffb16bd4a00e603ced2e790c3661d41a594c5"
      ],
      [
        "p",
        "73700987425c23a9b2922983621ffb16bd4a00e603ced2e790c3661d41a594c5"
      ],
      [
        "a",
        "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
      ],
      [
        "role",
        "revoked"
      ]
    ],
    "content": "",
    "sig": "64cbfba7dd6a59adafcf91facd2a6933c1a650fbdc304e31966323a5978c9a0654ff8cc79540349e26bb7c882599c148aa208f2443bf86e52074c907ceb0f654"
  },
  {
    "id": "2654310dda04f6d3ee041265258c812de36c855ece2ff37a9263d5ac6b4922af",
    "pubkey": "f6e0f5ae30d4cf5cfa7a68b75940412df98885bea580a211dc643c3329cbdcd0",
    "created_at": 1750000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "confboard:f6e0f5ae30d4cf5cfa7a68b75940412df98885bea580a211dc643c3329cbdcd0:e1"
      ],
      [
        "p",
        "f6e0f5ae30d4cf5cfa7a68b75940412df98885bea580a211dc643c3329cbdcd0"
      ],
      [
        "a",
        "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
      ],
      [
        "role",
        "contributor"
      ],
      [
        "cek",
        "An9eVHOJ3OsPdl9LQUIOTxCrwNPqzu4oCTJZ4xasdzBpYn734VRUzRv33kLXvWEy58g5R5nhf1HoWISaZpWr28fWLxo7+OBKIgqP6szC36Tq3dSKdu5E7pRcxDX9m77cBgtgWz0DwyFMsTwurqhPqzkoGtqrdcmynWjtAee8467ld7Y="
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "",
    "sig": "3de6019d3284a061449cc91ebce53db68c5ae4cf11b3f6802ea528c0eb8e971dd53ad7c3909b32f4f96c9f47db93aa92a5b2fae7bff5d3020ae7c672e08948f6"
  }
];

export const cardEpoch1A: NostrEvent = {
  "id": "996a9d3a2ad7a1bff29bda924099d62cee99f46d796ac6a0dacec6daa26db48a",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000200,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-001"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ],
    [
      "l",
      "22ea559d95457c0283b3f23e1341208e8d33464db1edf9e9048bb9f68c6141a2"
    ],
    [
      "l",
      "1b3019902f8fc42be57ec4b92df1618fd5b92bfc1c6c9be4e648d7492b746cef"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "sSuOfiZb4XMY4wespG8YqLf0NYOUuGjw/AtorWYkYe5zEOUJj9Ujqnp0t60BfW9NsTqTY91Xma2Cz7EkMc3v6cWaJXxY7aUiZV9UPtns2azmloZNy6+cvm1CCFdpe2uRKos2OW8bdyAMa7RHp3Opf13LJYDe66m/n7lps0gJ8QS5af9OflgwUjGA6jnI4KYCa8x+ni/hFDOjPxG84YZxs3r84iZtLODYnFhoGsYPH9UfC49uSKRC4z+Gr2kxd4B5RxKr3AAvvy+ppuDdqGGRoVJiy3M=",
  "sig": "d34cd77baab7649767522c35dc66c8bde9ffa119df3e8903644e1121f19b974b619b2785b02da9a8140bddf36f0198ad2193e6933bb8bc4014b80221ed1d7e6a"
};

export const cardEpoch1B: NostrEvent = {
  "id": "32b8353734fe66e45cc2de31c0c0313f9e260c52b04b0e96c5be93e7195937f8",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000210,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-002"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "inbox"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "tn6rIsKSWZverVn6lFX8Mo8e2rmERQuUyqMiJZf8pm0ETMTNv8swaXEDXIO0cyOfE8nuMTyyNqQZGR49DWe0M72pnoTAjuw8CWDqOM8T04UzTU3di09UDcQDoww8cCwCUXIyPVETRFFU4QTpbhbmCa8er8yrD5I7j8YfQ1RB+Ag=",
  "sig": "ae132f1eb5c501ba3b645617191352890c4e16f6ea3d385c1384f7f5c453fce40b2a177ab271e8f1ba1edccdde518c7e465025cc61bb31e2d3403c98b506f937"
};

export const cardEpoch2: NostrEvent = {
  "id": "6b4ee524abd7233510a440ea208fca6e809cc742b2829b49b8576873e4566353",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000400,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-003"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p0"
    ],
    [
      "priority",
      "p0"
    ],
    [
      "itype",
      "decision"
    ],
    [
      "l",
      "22ea559d95457c0283b3f23e1341208e8d33464db1edf9e9048bb9f68c6141a2"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "2"
    ]
  ],
  "content": "FtQJ/GJ881OCN48Eq+BsBULuzPK541XKnw5Oi6PUBwhn/SO1cr3MgKZqg3uZ+G1LQfl+ahqMFqS/5dh2tySehyKfhave97x6GRWpEimUzH/8EBDVhaSIdWtoecwq/3K42/zXiS6Vrf1xEzneZ6vavyopkX1RfgAQhkR+XXmhv1V8R+l9Aa6HVU4kvTCjnxxbpA4=",
  "sig": "d7892770d4d6d9f546c087735df3cebb27b2677559c56eba09b9a7b3f1fd595b46f86d28838b2eedaf33733cece4c70369030fc26e9312ef2ed91c6b3ba9c8b4"
};

export const cardEpochNobodyHolds: NostrEvent = {
  "id": "cbca68ab96569c5a706655a9653077cc132c444a4e6c2c4d7624baccacea824d",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000400,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-004"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p3"
    ],
    [
      "priority",
      "p3"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "9"
    ]
  ],
  "content": "jw5SLasV1aty0evZ+jPJFD6IlFhDbxohSTfi5kZoV5qnI8rtPYyygkcmc79rJppG+bdGprdNAe/VKqREgIWGqayGPY2nZKlwdpE=",
  "sig": "1c4a779c28444ba735c1c39d44d6e5b55af624dc627d7a6c5b72751ee1c04e230c88117d6526a1a39ce97342f76593f3dd60d2eee9778ff4f2212b387e5277fd"
};

export const cardSmuggledCleartext: NostrEvent = {
  "id": "6f5ad79010da2596df4d8060594f56dfa5a9c62d7c75579c17b20dc35bfa248a",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000500,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-005"
    ],
    [
      "title",
      "SMUGGLED CLEARTEXT TITLE"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ]
  ],
  "content": "SMUGGLED CLEARTEXT BODY",
  "sig": "ac5d6c2846d1f57283ec20f60e4310a7adc7749aaf5805c4780a85902400b55c6e3ddc360e5063f69340639ae0e90a8ff0a8fbea0f424aef8ddce0d06a965055"
};

export const cardGrandfatheredPlaintext: NostrEvent = {
  "id": "bfcff6f6ed66d36d4df188072ed21eed77597024d588b48405e7b1d9778a6260",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1749999000,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-006"
    ],
    [
      "title",
      "Legacy plaintext card"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "done"
    ],
    [
      "rank",
      "p3"
    ],
    [
      "priority",
      "p3"
    ],
    [
      "itype",
      "task"
    ]
  ],
  "content": "Authored before the board went confidential.",
  "sig": "fd537e857e9d1ba5b1ec45d8c448658a1b8d81e5f072e3fce0f40713312a648ef3b718da3649882fd64fe29bafffd2e4c17c2ced957415b209c590f5d1f31e49"
};

export const cardForgedSignature: NostrEvent = {
  "id": "cf80bd972d5edd0570e9ba1e5ae5c021c850975c438d0d4e21061231280aa8b3",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000200,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-007"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p0"
    ],
    [
      "priority",
      "p0"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "s5x6o+3gvEunEZwn+Eo6RwQ/ayUY2ubUP/32fyxqB21TvtuZK7/hcbRIrAqeE/hCuk6+ZAPkwwAcFOagGgpSLXyVgCl8",
  "sig": "6759e490b61d41c5c78a560008001b77907974a0faea0ef98f4da7823d4ead8aebc30a0fe910532dd00b9a568ac9064423d5a99d0789b379729624e23e82d8f1"
};

export const cardSealedNonObject: NostrEvent = {
  "id": "3798ab3169d5e52b5878779c5955f75512a3902cf77f149231efdfd6082141a9",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000220,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-008"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "DD4HDuXDy6rQqh4oK8CKxHiE/78qaXWwZr0YkMLuvqQTz8GsbHDXYHPNpoB0qZfa1A==",
  "sig": "6021d2db5a6e13fba5471a52a3b1459b83320d0b422722ee3c2f09d029379f999222cc18678cb19b62d9d7a1a72088bce8dbca44b91723e6600987e6ff96a048"
};

export const cardSealedNoTitle: NostrEvent = {
  "id": "f989ee2db3380c2d5cd27607b64525ac1a41a626119a9bf27a8172aa7fe17112",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000230,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-009"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "OzCnNRjEKVMHavmZVHcWpa5S/NxiIHUrOd0Tre7PZgRUK0RbvGTZUxPh8yLP2MmsekHesQk52uRCd6zMmS01GSTqs7M+KyhKWkxzwl3z",
  "sig": "bb5077d6efcc1475dc24f01506cf1e46cbcd600f6d8f9b6c25c04363c10df7baa47940225452a0835596a5a030886543b9bd858f74a1d6f28e5c27c60af82c92"
};

/** ready-daf round 2: the owner CEK grant for epoch 1 signed AFTER the rotation.
 * NOT part of `grants` — served alone, it establishes a cutover far later than the
 * truth while leaving the epoch set covered from 1. */
export const grantEpoch1Late: NostrEvent = {
  "id": "a97a7ef5a2f5fa73faf834e261c2e383daab87e7920fd2f047015b2d677c8877",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000600,
  "kind": 39301,
  "tags": [
    [
      "d",
      "confboard:a97a43be2137eb35bd85b85ce1ce3ceb674c8dab32c5cb3575d4bec34b310af6:e1"
    ],
    [
      "p",
      "a97a43be2137eb35bd85b85ce1ce3ceb674c8dab32c5cb3575d4bec34b310af6"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "role",
      "contributor"
    ],
    [
      "cek",
      "AjEqDOGG53QTu94k+a4vWvKWK3a0Bd/4CWKoEEsfMmUm0cUVaeJcCyG6HwgjZnSByU/9wMHPc80KdmSonT2/kVZ6Bx6RhgoibnMaWghPM7yBVO39KxQnlPSVAjnmQPDhPSySzdtsoaj5Qofd9kbUZ2AJtTJ2qG7imVOI1JO7n9O8Z58="
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "",
  "sig": "fc5f7804e79a7e3e5ac11b098adc4bf24db03e653f44149ed46309ac9f81b6c68b503056b82bc4647d991834e9632ebc1ebfbdf75522473fbc72d55fffb83c29"
};

/** ready-daf round 2: owner-signed PLAINTEXT authored between the true cutover
 * and the rotation. Post-cutover cleartext that a manufactured late cutover
 * grandfathers in. NOT part of `cards`. */
export const cardGapPlaintext: NostrEvent = {
  "id": "55e42ba7a5c9784646929f76c441f685fc05b39c997f8f62e27122429525b7f4",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000205,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-010"
    ],
    [
      "title",
      "GAP CLEARTEXT TITLE"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ]
  ],
  "content": "GAP CLEARTEXT BODY",
  "sig": "b9a7b47fc19f478032a1de55c2fcebd9edcfc909f38c17123193c0ed8beaf170c29e8f26adcd0645545f0915aab2b1ee77b1585fb49d9ecd221a6d9e59f102b4"
};

/** ready-daf round 2: sealed under epoch 1, published after the rotation. Its
 * epoch is the only thing about it that witnesses a withheld grant. NOT part of
 * `cards`. */
export const cardEpoch1AfterRotation: NostrEvent = {
  "id": "899cb04e15bf32379b371dd45431f0a8778012a106a97e7f594c9c866b867eab",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000700,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-011"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p2"
    ],
    [
      "priority",
      "p2"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "1"
    ]
  ],
  "content": "oH66/pxvKSqi6/B2O/T9VcfRzy/mg5Guu+M61n6PFuPQIEymRRoPvLtJ/MtWsr3fYwJSDzeS35SBtJdVMTfrDiDe4Iu+Rt2wBdOtSEYy4hLUOTMF1txL++6Lg1vci71bvGmz2jVtyttuju+9VQhd1l8TnQmZODaWkquqpCv7lHdUHWzNBKBflJhYHA==",
  "sig": "b1e67d867c7a288640ac970066d74c340aba02aa7d147e5b7e013ac7631fd37917078fa00fff1645c825670fd6efb8e80ed5299a72c63d2a7ec28542a77c396c"
};

/** ready-470: an epoch-3 grant to MEMBER whose CEK is sealed as 32 RAW bytes,
 * the way WrapKey did before ready-c4b. rd reads it; a NIP-07 browser signer
 * returns a string and the bytes do not survive the UTF-8 decode, so the key is
 * silently destroyed. NOT part of `grants`. */
export const legacyRawWrapGrant: NostrEvent = {
  "id": "76fe090fa116bd49710c0c54b186aae36318d5565e2dacf9aef16dc6e3f09ce7",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000800,
  "kind": 39301,
  "tags": [
    [
      "d",
      "confboard:9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68:e3"
    ],
    [
      "p",
      "9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "role",
      "contributor"
    ],
    [
      "cek",
      "ApGWp5pvzmgtB+S6Z/THqzgGblK5p8I/qv2Y3DTqjZ7DwsJkzsk24IrH+TORwNo/35cHZ76npEjSr8wQaB9oqnRGcqL59XUQZo/hjbTRAwZq+3efTr9ifioA/M1e78O5V3OC"
    ],
    [
      "cek_epoch",
      "3"
    ]
  ],
  "content": "",
  "sig": "cd2c966f1b2804e717e864203cee8c8aa09107ccc28e5d66cf20f99fe00d96b1ceaeee0706c071af728ab1597692c25da4b287f3512fdf698f0465846e6dd98a"
};

/** ready-470: what `rd confidential rewrap` publishes over legacyRawWrapGrant —
 * the SAME CEK_EPOCH3 value, the same epoch, the same addressable `d` slot, one
 * second later, sealed as 64 hex characters. NOT part of `grants`. */
export const rewrappedHexGrant: NostrEvent = {
  "id": "61d6eb283413a00ad59097851241fb8357b0aa7cec328b3663cdfd92c9a011d2",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000801,
  "kind": 39301,
  "tags": [
    [
      "d",
      "confboard:9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68:e3"
    ],
    [
      "p",
      "9579da11acd6a4c7e1c3b0f9404ead2720bf8e68931eff66632b0c05c179bb68"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "role",
      "contributor"
    ],
    [
      "cek",
      "AjGWQ7E+UcZ0i27VAXT7JqYMMn/ZK2jexqvSqHkPnYw1A+A/1v3jnH+kN4spztY+mXhf6qyeH9NLCcZKmuBzOO82P1K+Kgi0Mvo8ZuTyp/kaCAeUtKl5mrcWK46gFz4F1Etw3Id5tWSeqlyhceKG8v7mqim75Vdk7lDKan8Jr3Im5X8="
    ],
    [
      "cek_epoch",
      "3"
    ]
  ],
  "content": "",
  "sig": "dc4cd2d0eb409b1b508685ea34a12a24054d40ab40fcb9f851c9a19f3335ef42002a22544bc051f4993392bc86b0042e275893a462e5cf6ff8d6246190c5dc65"
};

/** ready-470: the same legacy/repaired pair addressed to the OWNER's own key —
 * the state the ready board's own self-grant was in, and the reason the board page
 * showed [encrypted] to the person who owns it. NOT part of `grants`. */
export const legacyRawWrapGrantOwner: NostrEvent = {
  "id": "f320dd516dc8b85e605d3c4d77858b817d70525f902415d4dad0a51b7dd42e66",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000800,
  "kind": 39301,
  "tags": [
    [
      "d",
      "confboard:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:e3"
    ],
    [
      "p",
      "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "role",
      "owner"
    ],
    [
      "cek",
      "AlWLhF+wiv1WlboGjGOjOmCsX9kjQ40j7DJpHin4SguKZ7ohFWwVgvWjRiFnfFWm8fTF/GGmh7fjLOhBkwJ2OyknRF4LPxPSHshMtmXTo9zys6Kbj6WuPOmvgWjo0LNrlANb"
    ],
    [
      "cek_epoch",
      "3"
    ]
  ],
  "content": "",
  "sig": "21dfd733b1e4da175309b47146d6ec82710b8240eacf4babc65c1ad8ec1a97c6e860112f3a5d8da479d89e7500fe8d023672dd461b8e09c7488db128f1ff5d3c"
};

export const rewrappedHexGrantOwner: NostrEvent = {
  "id": "51c8b620b7e1dfc96beb3bd1bac5778380addf261fa12bd98e1ec8e146ee9158",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000801,
  "kind": 39301,
  "tags": [
    [
      "d",
      "confboard:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:e3"
    ],
    [
      "p",
      "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "role",
      "owner"
    ],
    [
      "cek",
      "Asw+J7OOzgYslPmiJrOFT3I5lELZ/WfU/fEuxeML16QyhpVExK6t/+3gQBjJ7igvUQ1Q62HqjxhBjpZ+PXb5pR3Sd7RmTlKiXwD1zkmq369Oa1zUlKDcFKtu8jmqmz452a+ZHy1XzwgI6+zku+GL8uLvUFgH4XyfPwD+iKFu9QNGKa0="
    ],
    [
      "cek_epoch",
      "3"
    ]
  ],
  "content": "",
  "sig": "24cf1efbc15ec440b930ef2f87971d5fb66e74c45bd031951a541046a284a45ff494047fd0fa721b9bb83a8501343f07e61488c67b9a7f7973cd50c58f894d63"
};

/** ready-470: a card sealed under epoch 3, whose title renders in the page only
 * if the reader's epoch-3 wrap survived the NIP-07 string boundary. NOT part of
 * `cards`. */
export const cardSealedUnderEpoch3: NostrEvent = {
  "id": "6041bb6c11fc6eb37f5711b17241fd249f1cd7f81df2bbcddd0234fd3a4168a7",
  "pubkey": "4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523",
  "created_at": 1750000900,
  "kind": 30302,
  "tags": [
    [
      "d",
      "conf-012"
    ],
    [
      "a",
      "30301:4063c506e6cbf28efddce41791a2e251ab9512cf97b4e7e0c47ab1c768cd3523:confboard"
    ],
    [
      "s",
      "active"
    ],
    [
      "rank",
      "p1"
    ],
    [
      "priority",
      "p1"
    ],
    [
      "itype",
      "task"
    ],
    [
      "enc",
      "1"
    ],
    [
      "cek_epoch",
      "3"
    ]
  ],
  "content": "i5kp5+gY68cf8oTQxC0k7SkFbmgsn6dsvzK905W5k/STxWk6RctuRcIzft/fcp2VIagtTvCh4T3DtbHrmve2yfk0aYLBzHhL7SN/56jcQj4lKcwmTtrm7av/vHhYgnUp8OGTexb6furxXzCumJXEf2BiMc7K61BdP2u5ThNvSZfMAfTKKiN+xjFbaStSPC0fNPpaumzZm2RM6A==",
  "sig": "ff09afc164d7a8440f23873a85b0af33a93957845150507b401698b73d1d161e7129584e8be1f1eddeeec689ffb737ad729078b1a9ae940441e4207a57f799b3"
};

/** Every confidential card in the fixture, in relay-delivery order. */
export const cards: NostrEvent[] = [
  cardEpoch1A,
  cardEpoch1B,
  cardEpoch2,
  cardEpochNobodyHolds,
  cardSmuggledCleartext,
  cardGrandfatheredPlaintext,
  cardForgedSignature,
  cardSealedNonObject,
  cardSealedNoTitle,
];

/** The plaintext the Go writer sealed, item for item — what the browser must reproduce. */
export const expectedPlaintext = [
  {
    "id": "conf-001",
    "title": "Ship the confidential board UI",
    "context": "Titles must render for a granted member and fail closed otherwise.",
    "waiting_on": "the relay allowlist",
    "labels": [
      "crypto",
      "board"
    ],
    "epoch": 1
  },
  {
    "id": "conf-002",
    "title": "Rotate the CEK on revoke",
    "context": "Epoch N+1 is wrapped to the remaining members only.",
    "waiting_on": "",
    "labels": [],
    "epoch": 1
  },
  {
    "id": "conf-003",
    "title": "Sealed after the rotation",
    "context": "Only a reader holding epoch 2 can read this one.",
    "waiting_on": "",
    "labels": [
      "crypto"
    ],
    "epoch": 2
  }
] as const;
