// @vitest-environment jsdom
//
// The rd1_ token fixture below was generated by the REAL Go
// buildNostrClaimToken (cmd/rd/nostr_invite.go) — not hand-encoded — via a
// throwaway `go test` in cmd/rd calling it directly and printing the result
// (see the item's ground_truth_evidence for the exact commands). This proves
// parseFragment decodes exactly what `rd board share` / `rd invite` mint.
import { describe, expect, it, vi } from "vitest";
import { parseFragment, parseAndStripFragment } from "./fragment";
import { bytesToHex } from "./sha256";

// Generated by: go test ./cmd/rd/ -run TestZZPrintClaimTokenFixture -v
// buildNostrClaimToken("30301:abc123:myboard", ["wss://relay.3dl.network"], "deadbeef", 1700000000, 1700003600, "abc123")
const REAL_RD1_TOKEN =
  "rd1_eyJ2IjozLCJib2FyZCI6IjMwMzAxOmFiYzEyMzpteWJvYXJkIiwicmVsYXlzIjpbIndzczovL3JlbGF5LjNkbC5uZXR3b3JrIl0sImNsYWltIjoiZGVhZGJlZWYiLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MTcwMDAwMzYwMCwiaXNzIjoiYWJjMTIzIn0";

describe("parseFragment", () => {
  it("decodes a real rd1_ claim token minted by the Go CLI", () => {
    const parsed = parseFragment("#" + REAL_RD1_TOKEN);
    expect(parsed.kind).toBe("claim");
    if (parsed.kind !== "claim") throw new Error("unreachable");
    expect(parsed.payload).toEqual({
      v: 3,
      board: "30301:abc123:myboard",
      relays: ["wss://relay.3dl.network"],
      claim: "deadbeef",
      iat: 1700000000,
      exp: 1700003600,
      iss: "abc123",
    });
  });

  it("works without the leading # too (parseFragment accepts raw hash content)", () => {
    const parsed = parseFragment(REAL_RD1_TOKEN);
    expect(parsed.kind).toBe("claim");
  });

  it("rejects a truncated rd1_ token", () => {
    expect(() => parseFragment("#rd1_")).toThrow();
  });

  it("rejects a v2 (legacy) token shape", () => {
    const json = JSON.stringify({ v: 2, sk: "deadbeef" });
    const b64 = btoa(json).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
    expect(() => parseFragment("#rd1_" + b64)).toThrow();
  });

  it('parses the own-board "#board=...&relays=..." shape (cmd/rd/board.go ownBoardURL)', () => {
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard&relays=wss%3A%2F%2Frelay.3dl.network%2Cwss%3A%2F%2Fother.example");
    expect(parsed).toEqual({
      kind: "board",
      board: "30301:abc123:myboard",
      relays: ["wss://relay.3dl.network", "wss://other.example"],
    });
  });

  it('parses "#board=..." with no relays param as an empty relay list', () => {
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard");
    expect(parsed).toEqual({ kind: "board", board: "30301:abc123:myboard", relays: [] });
  });

  it("returns kind none for an empty hash", () => {
    expect(parseFragment("")).toEqual({ kind: "none" });
    expect(parseFragment("#")).toEqual({ kind: "none" });
  });
});

// ready-df0: the `rd board --with-key` shape. The fixture below is the exact
// fragment cmd/rd/board.go's ownBoardURL emits for a confidential board — its
// byte shape is pinned on the Go side by
// TestBoardCmd_WithKey_FragmentShapeMatchesBrowserParser (cmd/rd/board_test.go),
// which builds this same string from the real command output, so the two
// implementations cannot drift apart silently.
// ltk= APPEARS THROUGHOUT THIS BLOCK AND IS NO LONGER EMITTED. `rd board
// --with-key` dropped it on least-privilege grounds (nothing in this app reads
// an LTK — see fragment.ts's header), but a link minted by an older build still
// carries one and must still open. These cases are therefore the BACKWARD-
// COMPATIBILITY witness, not a description of what the CLI produces today: the
// emitted vocabulary is pinned on the Go side by
// TestBoardCmd_WithKey_FragmentParamAllowlist, which fails if ltk= comes back.
describe("parseFragment — `rd board --with-key` key material", () => {
  const CEK1 = "a".repeat(64);
  const CEK2 = "b".repeat(64);
  const LTK = "c".repeat(64);
  const PK = "d".repeat(64);
  const WITH_KEY_HASH =
    "#board=30301%3Aabc123%3Amyboard" +
    "&cek=1%3A" + CEK1 + "%2C2%3A" + CEK2 +
    "&ltk=" + LTK +
    "&pk=" + PK +
    "&relays=wss%3A%2F%2Frelay.3dl.network";

  it("decodes pk, every cek epoch, and a legacy ltk", () => {
    const parsed = parseFragment(WITH_KEY_HASH);
    if (parsed.kind !== "board") throw new Error("unreachable");
    expect(parsed.board).toBe("30301:abc123:myboard");
    expect(parsed.relays).toEqual(["wss://relay.3dl.network"]);
    expect(parsed.viewer).toBe(PK);
    expect(parsed.keys!.ceks.map((c) => c.epoch)).toEqual([1, 2]);
    expect(bytesToHex(parsed.keys!.ceks[0].key)).toBe(CEK1);
    expect(bytesToHex(parsed.keys!.ceks[1].key)).toBe(CEK2);
    expect(bytesToHex(parsed.keys!.ltk!)).toBe(LTK);
  });

  it("leaves viewer and keys ABSENT on the default (key-free) own-board link", () => {
    // The default `rd board` output must keep parsing to exactly what it parsed
    // to before ready-df0 — no viewer, so the login form still shows, and no
    // keys, so nothing is decrypted that a grant did not authorize.
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard&relays=wss%3A%2F%2Fr.example");
    if (parsed.kind !== "board") throw new Error("unreachable");
    expect(parsed.viewer).toBeUndefined();
    expect(parsed.keys).toBeUndefined();
  });

  it("carries a legacy ltk with no cek, without mistaking it for a key-free link", () => {
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard&ltk=" + LTK);
    if (parsed.kind !== "board") throw new Error("unreachable");
    expect(parsed.keys!.ceks).toEqual([]);
    expect(bytesToHex(parsed.keys!.ltk!)).toBe(LTK);
  });

  it("REJECTS damaged key material instead of half-decoding it", () => {
    // A truncated link is the realistic failure (a chat client eats the tail of
    // a long URL). Throwing routes it to main()'s "ask for a fresh link" notice;
    // a partial key would instead produce a board of unexplained placeholders.
    const bad = [
      "#board=30301%3Aabc123%3Amyboard&cek=1%3A" + CEK1.slice(0, 60), // truncated key
      "#board=30301%3Aabc123%3Amyboard&cek=" + CEK1, // no <epoch>: prefix
      "#board=30301%3Aabc123%3Amyboard&cek=0%3A" + CEK1, // epoch 0 (Go rejects <1)
      "#board=30301%3Aabc123%3Amyboard&cek=-1%3A" + CEK1, // negative epoch
      "#board=30301%3Aabc123%3Amyboard&cek=x%3A" + CEK1, // non-numeric epoch
      "#board=30301%3Aabc123%3Amyboard&cek=", // present but empty
      "#board=30301%3Aabc123%3Amyboard&ltk=" + LTK.slice(0, 32), // truncated ltk
      "#board=30301%3Aabc123%3Amyboard&ltk=" + "z".repeat(64), // not hex
      "#board=30301%3Aabc123%3Amyboard&pk=" + PK.slice(0, 30), // truncated pubkey
    ];
    for (const hash of bad) {
      expect(() => parseFragment(hash), hash).toThrow();
    }
  });
});

describe("parseAndStripFragment", () => {
  it("strips the fragment from the URL after parsing (done condition 6)", () => {
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const loc = { hash: "#" + REAL_RD1_TOKEN, pathname: "/board", search: "" } as unknown as Location;

    const parsed = parseAndStripFragment(loc);
    expect(parsed.kind).toBe("claim");
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");
    replaceState.mockRestore();
  });

  it("ready-df0: strips a KEY-BEARING fragment, on the success path and on the throw path alike", () => {
    // The strip is what makes shipping a CEK in a URL tolerable at all, so it
    // is asserted for both outcomes: a good key link, and a damaged one whose
    // parse throws (ready-62d1's `finally` — the case where a key most wants
    // removing from the address bar and from history).
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const key = "a".repeat(64);

    const good = { hash: `#board=30301%3Aabc%3Ab&pk=${"d".repeat(64)}&cek=1%3A${key}`, pathname: "/board", search: "" } as unknown as Location;
    expect(parseAndStripFragment(good).kind).toBe("board");
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");

    replaceState.mockClear();
    const damaged = { hash: `#board=30301%3Aabc%3Ab&cek=1%3A${key.slice(0, 40)}`, pathname: "/board", search: "" } as unknown as Location;
    expect(() => parseAndStripFragment(damaged)).toThrow();
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");
    replaceState.mockRestore();
  });

  it("does not touch history when there was no fragment", () => {
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const loc = { hash: "", pathname: "/board", search: "" } as unknown as Location;
    parseAndStripFragment(loc);
    expect(replaceState).not.toHaveBeenCalled();
    replaceState.mockRestore();
  });
});

