// @vitest-environment jsdom
//
// The rd1_ token fixture below was generated by the REAL Go
// buildNostrClaimToken (cmd/rd/nostr_invite.go) — not hand-encoded — via a
// throwaway `go test` in cmd/rd calling it directly and printing the result
// (see the item's ground_truth_evidence for the exact commands). This proves
// parseFragment decodes exactly what `rd board share` / `rd invite` mint.
import { describe, expect, it, vi } from "vitest";
import { parseFragment, parseAndStripFragment } from "./fragment";
import { bytesToHex } from "./sha256";
import { portfolioKeyVectors } from "./portfoliovectors.fixtures";

// Generated by: go test ./cmd/rd/ -run TestZZPrintClaimTokenFixture -v
// buildNostrClaimToken("30301:abc123:myboard", ["wss://relay.3dl.network"], "deadbeef", 1700000000, 1700003600, "abc123")
const REAL_RD1_TOKEN =
  "rd1_eyJ2IjozLCJib2FyZCI6IjMwMzAxOmFiYzEyMzpteWJvYXJkIiwicmVsYXlzIjpbIndzczovL3JlbGF5LjNkbC5uZXR3b3JrIl0sImNsYWltIjoiZGVhZGJlZWYiLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MTcwMDAwMzYwMCwiaXNzIjoiYWJjMTIzIn0";

describe("parseFragment", () => {
  it("decodes a real rd1_ claim token minted by the Go CLI", () => {
    const parsed = parseFragment("#" + REAL_RD1_TOKEN);
    expect(parsed.kind).toBe("claim");
    if (parsed.kind !== "claim") throw new Error("unreachable");
    expect(parsed.payload).toEqual({
      v: 3,
      board: "30301:abc123:myboard",
      relays: ["wss://relay.3dl.network"],
      claim: "deadbeef",
      iat: 1700000000,
      exp: 1700003600,
      iss: "abc123",
    });
  });

  it("works without the leading # too (parseFragment accepts raw hash content)", () => {
    const parsed = parseFragment(REAL_RD1_TOKEN);
    expect(parsed.kind).toBe("claim");
  });

  it("rejects a truncated rd1_ token", () => {
    expect(() => parseFragment("#rd1_")).toThrow();
  });

  it("rejects a v2 (legacy) token shape", () => {
    const json = JSON.stringify({ v: 2, sk: "deadbeef" });
    const b64 = btoa(json).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
    expect(() => parseFragment("#rd1_" + b64)).toThrow();
  });

  it('parses the own-board "#board=...&relays=..." shape (cmd/rd/board.go ownBoardURL)', () => {
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard&relays=wss%3A%2F%2Frelay.3dl.network%2Cwss%3A%2F%2Fother.example");
    expect(parsed).toEqual({
      kind: "board",
      board: "30301:abc123:myboard",
      relays: ["wss://relay.3dl.network", "wss://other.example"],
    });
  });

  it('parses "#board=..." with no relays param as an empty relay list', () => {
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard");
    expect(parsed).toEqual({ kind: "board", board: "30301:abc123:myboard", relays: [] });
  });

  it("returns kind none for an empty hash", () => {
    expect(parseFragment("")).toEqual({ kind: "none" });
    expect(parseFragment("#")).toEqual({ kind: "none" });
  });
});

// ready-df0: the `rd board --with-key` shape. The fixture below is the exact
// fragment cmd/rd/board.go's ownBoardURL emits for a confidential board — its
// byte shape is pinned on the Go side by
// TestBoardCmd_WithKey_FragmentShapeMatchesBrowserParser (cmd/rd/board_test.go),
// which builds this same string from the real command output, so the two
// implementations cannot drift apart silently.
// ltk= APPEARS THROUGHOUT THIS BLOCK AND IS NO LONGER EMITTED. `rd board
// --with-key` dropped it on least-privilege grounds (nothing in this app reads
// an LTK — see fragment.ts's header), but a link minted by an older build still
// carries one and must still open. These cases are therefore the BACKWARD-
// COMPATIBILITY witness, not a description of what the CLI produces today: the
// emitted vocabulary is pinned on the Go side by
// TestBoardCmd_WithKey_FragmentParamAllowlist, which fails if ltk= comes back.
describe("parseFragment — `rd board --with-key` key material", () => {
  const CEK1 = "a".repeat(64);
  const CEK2 = "b".repeat(64);
  const LTK = "c".repeat(64);
  const PK = "d".repeat(64);
  const WITH_KEY_HASH =
    "#board=30301%3Aabc123%3Amyboard" +
    "&cek=1%3A" + CEK1 + "%2C2%3A" + CEK2 +
    "&ltk=" + LTK +
    "&pk=" + PK +
    "&relays=wss%3A%2F%2Frelay.3dl.network";

  it("decodes pk, every cek epoch, and a legacy ltk", () => {
    const parsed = parseFragment(WITH_KEY_HASH);
    if (parsed.kind !== "board") throw new Error("unreachable");
    expect(parsed.board).toBe("30301:abc123:myboard");
    expect(parsed.relays).toEqual(["wss://relay.3dl.network"]);
    expect(parsed.viewer).toBe(PK);
    expect(parsed.keys!.ceks.map((c) => c.epoch)).toEqual([1, 2]);
    expect(bytesToHex(parsed.keys!.ceks[0].key)).toBe(CEK1);
    expect(bytesToHex(parsed.keys!.ceks[1].key)).toBe(CEK2);
    expect(bytesToHex(parsed.keys!.ltk!)).toBe(LTK);
  });

  it("leaves viewer and keys ABSENT on the default (key-free) own-board link", () => {
    // The default `rd board` output must keep parsing to exactly what it parsed
    // to before ready-df0 — no viewer, so the login form still shows, and no
    // keys, so nothing is decrypted that a grant did not authorize.
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard&relays=wss%3A%2F%2Fr.example");
    if (parsed.kind !== "board") throw new Error("unreachable");
    expect(parsed.viewer).toBeUndefined();
    expect(parsed.keys).toBeUndefined();
  });

  it("carries a legacy ltk with no cek, without mistaking it for a key-free link", () => {
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard&ltk=" + LTK);
    if (parsed.kind !== "board") throw new Error("unreachable");
    expect(parsed.keys!.ceks).toEqual([]);
    expect(bytesToHex(parsed.keys!.ltk!)).toBe(LTK);
  });

  it("REJECTS damaged key material instead of half-decoding it", () => {
    // A truncated link is the realistic failure (a chat client eats the tail of
    // a long URL). Throwing routes it to main()'s "ask for a fresh link" notice;
    // a partial key would instead produce a board of unexplained placeholders.
    const bad = [
      "#board=30301%3Aabc123%3Amyboard&cek=1%3A" + CEK1.slice(0, 60), // truncated key
      "#board=30301%3Aabc123%3Amyboard&cek=" + CEK1, // no <epoch>: prefix
      "#board=30301%3Aabc123%3Amyboard&cek=0%3A" + CEK1, // epoch 0 (Go rejects <1)
      "#board=30301%3Aabc123%3Amyboard&cek=-1%3A" + CEK1, // negative epoch
      "#board=30301%3Aabc123%3Amyboard&cek=x%3A" + CEK1, // non-numeric epoch
      "#board=30301%3Aabc123%3Amyboard&cek=", // present but empty
      "#board=30301%3Aabc123%3Amyboard&ltk=" + LTK.slice(0, 32), // truncated ltk
      "#board=30301%3Aabc123%3Amyboard&ltk=" + "z".repeat(64), // not hex
      "#board=30301%3Aabc123%3Amyboard&pk=" + PK.slice(0, 30), // truncated pubkey
    ];
    for (const hash of bad) {
      expect(() => parseFragment(hash), hash).toThrow();
    }
  });
});

// ---------------------------------------------------------------------------
// ready-de7 — A CEK IS BOUND TO A pk=, BECAUSE pk= IS WHAT MAKES THE SESSION
// READ-ONLY.
//
// keyring.ts's applyFragmentKeys deliberately skips the four checks
// deriveBoardKeyring runs on a relay-served grant. Half of the reason is
// provenance (the key came from the reader's own `rd`, which ran those checks
// locally); the OTHER half is that the session holding it cannot sign, so the
// key buys reading and nothing else. main.ts delivers that second half by
// minting `method: "readOnly"` — but only for a fragment that names a viewer in
// `pk=`.
//
// So `#board=<coord>&cek=<epoch>:<hex>` with NO pk= was the shape where the
// justification was simply false: no viewer meant main.ts showed the LOGIN
// FORM, and a visitor who logged in there with a NIP-07 extension held a
// SIGNING session that was nonetheless handed the link's CEKs (probed before
// the fix: the fixture's sealed titles opened for an `extension` identity).
// Binding the two parameters here is what makes the premise structural — after
// this, cek= implies pk= implies read-only — rather than a doc comment's
// assumption. The portfolio shape has always had this rule ("keys= without pk=
// is a damaged link"); the single-board shape was the asymmetry.
//
// The composition-level witness, that a signing session genuinely cannot obtain
// these keys through main(), is main.fragmentkey.test.ts's "A CEK CANNOT REACH
// A SIGNING SESSION".
// ---------------------------------------------------------------------------
describe("parseFragment — ready-de7: cek= without pk= is refused", () => {
  const CEK1 = "a".repeat(64);
  const CEK2 = "b".repeat(64);
  const LTK = "c".repeat(64);
  const PK = "d".repeat(64);
  const BOARD = "#board=30301%3Aabc123%3Amyboard";

  it("a one-epoch key link with no viewer throws instead of degrading to a login form", () => {
    expect(() => parseFragment(`${BOARD}&cek=1%3A${CEK1}`)).toThrow(/pk= is missing/);
  });

  it("the same holds for every held epoch, and with a legacy ltk alongside", () => {
    expect(() => parseFragment(`${BOARD}&cek=1%3A${CEK1}%2C2%3A${CEK2}`)).toThrow(/pk= is missing/);
    expect(() => parseFragment(`${BOARD}&cek=1%3A${CEK1}&ltk=${LTK}`)).toThrow(/pk= is missing/);
    // Order in the query string must not matter: URLSearchParams is a map, but
    // a reader of this file should not have to know that to trust the rule.
    expect(() => parseFragment(`${BOARD}&relays=wss%3A%2F%2Fr.test&cek=1%3A${CEK1}`)).toThrow(/pk= is missing/);
  });

  it("ANTI-TAUTOLOGY: the SAME link with pk= parses, keeps both epochs, and names the viewer", () => {
    // Without this, the throws above could be any old rejection of a cek= —
    // e.g. a rule that had accidentally banned key material outright.
    const parsed = parseFragment(`${BOARD}&pk=${PK}&cek=1%3A${CEK1}%2C2%3A${CEK2}`);
    if (parsed.kind !== "board") throw new Error("expected a board fragment");
    expect(parsed.viewer).toBe(PK);
    expect(parsed.keys!.ceks.map((c) => c.epoch)).toEqual([1, 2]);
  });

  it("a legacy ltk= WITHOUT pk= still parses — it decrypts nothing, so refusing it would strand an old link for no gain", () => {
    // The scope of the rule, stated as a case rather than left to the comment:
    // an LTK is the label-token key, nothing in this app reads BoardKeyring.ltk(),
    // and it cannot open a card envelope. Its only effect on the page is the
    // strictly tightening one (hasLinkKeys pushes confidentiality to "unknown").
    const parsed = parseFragment(`${BOARD}&ltk=${LTK}`);
    if (parsed.kind !== "board") throw new Error("expected a board fragment");
    expect(parsed.viewer).toBeUndefined();
    expect(parsed.keys!.ceks).toEqual([]);
    expect(parsed.keys!.ltk!.length).toBe(32);
  });

  it("THE INVARIANT, over every documented link shape: a fragment either throws or carries no decryption key without a viewer", () => {
    // A property over a table rather than one case, because the statement is
    // about the WHOLE parser: whatever shape a link arrives in, EITHER it is
    // refused, OR what comes back cannot decrypt a card without also telling
    // main.ts which pubkey to mint a read-only identity for. New shapes added to
    // this file are expected to be added here.
    //
    // Refusal counts as satisfying it — that is how the pk-less cek= shapes pass
    // — which also makes this loop sensitive to the fix being removed: drop the
    // guard and those shapes stop throwing, come back with CEKs and no viewer,
    // and the assertion inside fires.
    const shapes = [
      "", // plain visit
      "#relays=wss%3A%2F%2Fr.test",
      BOARD, // key-free own-board / share link
      `${BOARD}&relays=wss%3A%2F%2Fr.test`,
      `${BOARD}&pk=${PK}`, // --with-key on a PUBLIC board: viewer, no keys
      `${BOARD}&pk=${PK}&cek=1%3A${CEK1}`, // --with-key on a confidential board
      `${BOARD}&ltk=${LTK}`, // legacy, no decryption power
      `${BOARD}&pk=${PK}&cek=1%3A${CEK1}&ltk=${LTK}`, // legacy --with-key
      `${BOARD}&cek=1%3A${CEK1}`, // ready-de7: refused
      `${BOARD}&cek=1%3A${CEK1}%2C2%3A${CEK2}&relays=wss%3A%2F%2Fr.test`, // refused
      `#pk=${PK}`, // portfolio, key-free
      `#pk=${PK}&relays=wss%3A%2F%2Fr.test`,
    ];
    let sawDecryptionKeys = 0;
    let refused = 0;
    for (const hash of shapes) {
      let parsed;
      try {
        parsed = parseFragment(hash);
      } catch {
        refused++;
        continue;
      }
      if (parsed.kind === "board" && parsed.keys && parsed.keys.ceks.length > 0) {
        sawDecryptionKeys++;
        expect(parsed.viewer, `${hash} carries CEKs with no viewer`).toBeDefined();
      }
      if (parsed.kind === "portfolio") {
        // The portfolio variant types `viewer` as required, and parseFragment is
        // the only producer; assert it anyway so the invariant is checked, not
        // merely declared.
        expect(parsed.viewer, `${hash} is a portfolio link with no viewer`).toBeDefined();
      }
    }
    // ANTI-TAUTOLOGY, both ways: the loop proves nothing if no shape in it ever
    // carried a CEK, and nothing about the fix if every shape merely threw.
    expect(sawDecryptionKeys).toBe(2);
    expect(refused).toBe(2);
  });
});

describe("parseAndStripFragment", () => {
  it("strips the fragment from the URL after parsing (done condition 6)", () => {
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const loc = { hash: "#" + REAL_RD1_TOKEN, pathname: "/board", search: "" } as unknown as Location;

    const parsed = parseAndStripFragment(loc);
    expect(parsed.kind).toBe("claim");
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");
    replaceState.mockRestore();
  });

  it("ready-df0: strips a KEY-BEARING fragment, on the success path and on the throw path alike", () => {
    // The strip is what makes shipping a CEK in a URL tolerable at all, so it
    // is asserted for both outcomes: a good key link, and a damaged one whose
    // parse throws (ready-62d1's `finally` — the case where a key most wants
    // removing from the address bar and from history).
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const key = "a".repeat(64);

    const good = { hash: `#board=30301%3Aabc%3Ab&pk=${"d".repeat(64)}&cek=1%3A${key}`, pathname: "/board", search: "" } as unknown as Location;
    expect(parseAndStripFragment(good).kind).toBe("board");
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");

    replaceState.mockClear();
    const damaged = { hash: `#board=30301%3Aabc%3Ab&cek=1%3A${key.slice(0, 40)}`, pathname: "/board", search: "" } as unknown as Location;
    expect(() => parseAndStripFragment(damaged)).toThrow();
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");
    replaceState.mockRestore();
  });

  it("does not touch history when there was no fragment", () => {
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const loc = { hash: "", pathname: "/board", search: "" } as unknown as Location;
    parseAndStripFragment(loc);
    expect(replaceState).not.toHaveBeenCalled();
    replaceState.mockRestore();
  });
});


// ---------------------------------------------------------------------------
// ready-4d9 — the WHOLE-PORTFOLIO fragment: pk= with NO board=.
//
// The discriminator is an ABSENCE, which is worth testing carefully in both
// directions: a link that has board= must never be read as a portfolio link,
// and a link that lacks it must never fall through to the plain-visit path
// while carrying key material.
// ---------------------------------------------------------------------------
describe("parseFragment — portfolio links", () => {
  const PK = "d".repeat(64);
  // The real Go encoder's output, taken from the committed cross-language
  // vectors (see portfoliokeys.test.ts) rather than hand-encoded here.
  const VECTORS = portfolioKeyVectors;
  const ONE_BOARD = VECTORS[0];

  it("pk= with no board= is a portfolio link", () => {
    const parsed = parseFragment(`#pk=${PK}&relays=wss%3A%2F%2Fr.test`);
    expect(parsed.kind).toBe("portfolio");
    if (parsed.kind !== "portfolio") throw new Error("unreachable");
    expect(parsed.viewer).toBe(PK);
    expect(parsed.relays).toEqual(["wss://r.test"]);
    // No --with-key: no key material at all, and that is not an error.
    expect(parsed.keys).toBeUndefined();
  });

  it("keys= decodes into per-board key material", () => {
    const parsed = parseFragment(`#pk=${PK}&relays=wss%3A%2F%2Fr.test&keys=${ONE_BOARD.blob}`);
    if (parsed.kind !== "portfolio") throw new Error("expected a portfolio fragment");
    const coord = Object.keys(ONE_BOARD.boards)[0];
    expect([...parsed.keys!.keys()]).toEqual([coord]);
    expect(parsed.keys!.get(coord)!.ceks[0].key.length).toBe(32);
  });

  it("board= wins: a single-board link is never read as a portfolio link", () => {
    const parsed = parseFragment(`#board=30301%3Aabc%3Ab&pk=${PK}`);
    expect(parsed.kind).toBe("board");
  });

  it("board= together with keys= is rejected — a link is one board or the whole portfolio", () => {
    // Honouring both would make "which board does this key belong to" a
    // question with two answers.
    expect(() => parseFragment(`#board=30301%3Aabc%3Ab&pk=${PK}&keys=${ONE_BOARD.blob}`)).toThrow(/keys=/);
  });

  it("keys= without pk= is a damaged link, not a plain visit", () => {
    // The key material arrived but the identity it was minted for did not, so
    // the page could not open the right boards even holding their keys.
    expect(() => parseFragment(`#relays=wss%3A%2F%2Fr.test&keys=${ONE_BOARD.blob}`)).toThrow(/pk=/);
  });

  it("a TRUNCATED portfolio link throws rather than opening a smaller portfolio", () => {
    // The whole reason the blob is length-prefixed. Asserted here at the
    // fragment layer; portfoliokeys.test.ts proves it over every prefix.
    const big = VECTORS[VECTORS.length - 1];
    const full = `#pk=${PK}&relays=wss%3A%2F%2Fr.test&keys=${big.blob}`;
    // Sanity: the intact link parses and carries every board.
    const ok = parseFragment(full);
    if (ok.kind !== "portfolio") throw new Error("expected a portfolio fragment");
    expect(ok.keys!.size).toBe(24);
    // And every truncation of it — the blob is LAST in the fragment (see
    // cmd/rd/board_portfolio.go's portfolioURL), so a clipped link loses blob
    // bytes first and lands here rather than degrading into a bare login page.
    for (let cut = 1; cut < 200; cut++) {
      expect(() => parseFragment(full.slice(0, full.length - cut)), `truncated by ${cut}`).toThrow();
    }
  });

  it("a malformed pk= throws instead of opening as a half-pubkey", () => {
    expect(() => parseFragment(`#pk=${PK.slice(0, 40)}`)).toThrow(/pk=/);
  });

  it("a bare #relays= with no pk= and no board= is still a plain visit", () => {
    expect(parseFragment("#relays=wss%3A%2F%2Fr.test").kind).toBe("none");
  });

  it("strips a portfolio fragment from the address bar, throw or no throw", () => {
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});

    const good = { hash: `#pk=${PK}&keys=${ONE_BOARD.blob}`, pathname: "/board", search: "" } as unknown as Location;
    expect(parseAndStripFragment(good).kind).toBe("portfolio");
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");

    replaceState.mockClear();
    const damaged = { hash: `#pk=${PK}&keys=${ONE_BOARD.blob.slice(0, 30)}`, pathname: "/board", search: "" } as unknown as Location;
    expect(() => parseAndStripFragment(damaged)).toThrow();
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");
    replaceState.mockRestore();
  });
});

// ---------------------------------------------------------------------------
// ready-280: the board must reject non-wss relays from a link fragment
// instead of silently handing them to the connector. cmd/rd/board.go's
// browserOpenableRelays already narrows relays= at MINT time (ready-634), but
// that fix cannot reach into a link already sitting in someone's browser
// history or a link a sender hand-crafted — the fragment is the one part of
// a link that is never re-validated against the current build. This is the
// reader-side backstop, proven red-first: before this fix, parseRelays did
// no scheme check at all and every one of these would have kept the ws:// and
// junk-scheme entries in `relays`.
// ---------------------------------------------------------------------------
describe("parseFragment — ready-280 relay scheme filtering", () => {
  const MIXED_RELAYS =
    "wss%3A%2F%2Fgood.example" + // wss:// — always usable
    "%2Cws%3A%2F%2Fbad.example" + // ws:// — mixed content on a secure page
    "%2Cftp%3A%2F%2Fjunk.example"; // junk scheme — never a relay a client can open

  it('DELIVERABLE FIXTURE: a "board" link with wss + ws + a junk scheme keeps only wss:// on a secure page, and reports what was dropped', () => {
    const parsed = parseFragment(`#board=30301%3Aabc%3Ab&relays=${MIXED_RELAYS}`); // secure defaults to true
    if (parsed.kind !== "board") throw new Error("expected a board fragment");
    expect(parsed.relays).toEqual(["wss://good.example"]);
    expect(parsed.droppedRelays).toEqual(["ws://bad.example", "ftp://junk.example"]);
  });

  it("the same mixed list on a portfolio link: only wss:// kept, the rest reported", () => {
    const PK = "e".repeat(64);
    const parsed = parseFragment(`#pk=${PK}&relays=${MIXED_RELAYS}`);
    if (parsed.kind !== "portfolio") throw new Error("expected a portfolio fragment");
    expect(parsed.relays).toEqual(["wss://good.example"]);
    expect(parsed.droppedRelays).toEqual(["ws://bad.example", "ftp://junk.example"]);
  });

  it("an all-wss:// relay list carries no droppedRelays field at all", () => {
    const parsed = parseFragment("#board=30301%3Aabc%3Ab&relays=wss%3A%2F%2Fa.example%2Cwss%3A%2F%2Fb.example");
    if (parsed.kind !== "board") throw new Error("expected a board fragment");
    expect(parsed.relays).toEqual(["wss://a.example", "wss://b.example"]);
    expect(parsed.droppedRelays).toBeUndefined();
  });

  it("an explicitly insecure page context (secure=false) keeps ws:// alongside wss:// — but a junk scheme is still rejected regardless of page security", () => {
    const parsed = parseFragment(`#board=30301%3Aabc%3Ab&relays=${MIXED_RELAYS}`, false);
    if (parsed.kind !== "board") throw new Error("expected a board fragment");
    expect(parsed.relays).toEqual(["wss://good.example", "ws://bad.example"]);
    expect(parsed.droppedRelays).toEqual(["ftp://junk.example"]);
  });

  it("parseAndStripFragment derives secure from loc.protocol: an http:// page keeps ws://, an https:// page does not", () => {
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const hash = `#board=30301%3Aabc%3Ab&relays=${MIXED_RELAYS}`;

    const httpsLoc = { hash, protocol: "https:", pathname: "/board", search: "" } as unknown as Location;
    const onHttps = parseAndStripFragment(httpsLoc);
    if (onHttps.kind !== "board") throw new Error("expected a board fragment");
    expect(onHttps.relays).toEqual(["wss://good.example"]);

    const httpLoc = { hash, protocol: "http:", pathname: "/board", search: "" } as unknown as Location;
    const onHttp = parseAndStripFragment(httpLoc);
    if (onHttp.kind !== "board") throw new Error("expected a board fragment");
    expect(onHttp.relays).toEqual(["wss://good.example", "ws://bad.example"]);

    replaceState.mockRestore();
  });

  it("a relay list that is ENTIRELY dropped leaves an empty relays array (the board=/pk= branches then fall back to same-origin relays.json — see main.ts)", () => {
    const parsed = parseFragment("#board=30301%3Aabc%3Ab&relays=ws%3A%2F%2Fbad.example%2Cftp%3A%2F%2Fjunk.example");
    if (parsed.kind !== "board") throw new Error("expected a board fragment");
    expect(parsed.relays).toEqual([]);
    expect(parsed.droppedRelays).toEqual(["ws://bad.example", "ftp://junk.example"]);
  });
});
