// @vitest-environment jsdom
//
// The rd1_ token fixture below was generated by the REAL Go
// buildNostrClaimToken (cmd/rd/nostr_invite.go) — not hand-encoded — via a
// throwaway `go test` in cmd/rd calling it directly and printing the result
// (see the item's ground_truth_evidence for the exact commands). This proves
// parseFragment decodes exactly what `rd board share` / `rd invite` mint.
import { describe, expect, it, vi } from "vitest";
import { parseFragment, parseAndStripFragment } from "./fragment";

// Generated by: go test ./cmd/rd/ -run TestZZPrintClaimTokenFixture -v
// buildNostrClaimToken("30301:abc123:myboard", ["wss://relay.3dl.network"], "deadbeef", 1700000000, 1700003600, "abc123")
const REAL_RD1_TOKEN =
  "rd1_eyJ2IjozLCJib2FyZCI6IjMwMzAxOmFiYzEyMzpteWJvYXJkIiwicmVsYXlzIjpbIndzczovL3JlbGF5LjNkbC5uZXR3b3JrIl0sImNsYWltIjoiZGVhZGJlZWYiLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MTcwMDAwMzYwMCwiaXNzIjoiYWJjMTIzIn0";

describe("parseFragment", () => {
  it("decodes a real rd1_ claim token minted by the Go CLI", () => {
    const parsed = parseFragment("#" + REAL_RD1_TOKEN);
    expect(parsed.kind).toBe("claim");
    if (parsed.kind !== "claim") throw new Error("unreachable");
    expect(parsed.payload).toEqual({
      v: 3,
      board: "30301:abc123:myboard",
      relays: ["wss://relay.3dl.network"],
      claim: "deadbeef",
      iat: 1700000000,
      exp: 1700003600,
      iss: "abc123",
    });
  });

  it("works without the leading # too (parseFragment accepts raw hash content)", () => {
    const parsed = parseFragment(REAL_RD1_TOKEN);
    expect(parsed.kind).toBe("claim");
  });

  it("rejects a truncated rd1_ token", () => {
    expect(() => parseFragment("#rd1_")).toThrow();
  });

  it("rejects a v2 (legacy) token shape", () => {
    const json = JSON.stringify({ v: 2, sk: "deadbeef" });
    const b64 = btoa(json).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
    expect(() => parseFragment("#rd1_" + b64)).toThrow();
  });

  it('parses the own-board "#board=...&relays=..." shape (cmd/rd/board.go ownBoardURL)', () => {
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard&relays=wss%3A%2F%2Frelay.3dl.network%2Cwss%3A%2F%2Fother.example");
    expect(parsed).toEqual({
      kind: "board",
      board: "30301:abc123:myboard",
      relays: ["wss://relay.3dl.network", "wss://other.example"],
    });
  });

  it('parses "#board=..." with no relays param as an empty relay list', () => {
    const parsed = parseFragment("#board=30301%3Aabc123%3Amyboard");
    expect(parsed).toEqual({ kind: "board", board: "30301:abc123:myboard", relays: [] });
  });

  it("returns kind none for an empty hash", () => {
    expect(parseFragment("")).toEqual({ kind: "none" });
    expect(parseFragment("#")).toEqual({ kind: "none" });
  });
});

describe("parseAndStripFragment", () => {
  it("strips the fragment from the URL after parsing (done condition 6)", () => {
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const loc = { hash: "#" + REAL_RD1_TOKEN, pathname: "/board", search: "" } as unknown as Location;

    const parsed = parseAndStripFragment(loc);
    expect(parsed.kind).toBe("claim");
    expect(replaceState).toHaveBeenCalledWith(null, "", "/board");
    replaceState.mockRestore();
  });

  it("does not touch history when there was no fragment", () => {
    const replaceState = vi.spyOn(window.history, "replaceState").mockImplementation(() => {});
    const loc = { hash: "", pathname: "/board", search: "" } as unknown as Location;
    parseAndStripFragment(loc);
    expect(replaceState).not.toHaveBeenCalled();
    replaceState.mockRestore();
  });
});

