// Fixtures generated by the REAL Go implementation (pkg/nostr.Event.Sign),
// not hand-crafted here — this proves the TS canonical serialization + id
// derivation + BIP-340 verify are wire-compatible with the Go signer, not
// just internally self-consistent. Regenerate with:
//   go run <a small program calling nostr.GenerateKey()+Event.Sign()>
// (see the item's ground_truth_evidence for the exact program used).
import { describe, expect, it } from "vitest";
import { verifyEvent, computeEventId, tagValue, type NostrEvent } from "./nostrevent";

const PLAIN: NostrEvent = {
  id: "acfbe30d6646f6b8bed10bb3955f1296ab556378ec124aeb33a30a824912749f",
  pubkey: "2accb29ede887a446c2711124adc8363ab72168ade1614d92c6428f5fb895d44",
  created_at: 1700000000,
  kind: 30301,
  tags: [
    ["d", "alpha"],
    ["title", "Alpha Board"],
  ],
  content: "",
  sig: "34d0f3bf3c82ef13bc9e536df899ed3fe8c36bf3c939774f40f597e02f3de701f13ecbcf191d51cfe885dc08716a5d7f273dedb28ca8fd3607f2d5eda6a87fcf",
};

// Confidential-style event: no title tag, content with escaped quote,
// newline, tab, and a non-ASCII character — exercises serializeString's
// escape rules exactly like event.go's serializeString.
const CONFIDENTIAL: NostrEvent = {
  id: "5b56ba792b67314a79a89cd8d3cf14f2d9dd850b84eb8d1c0588e927dbcb03e7",
  pubkey: "2accb29ede887a446c2711124adc8363ab72168ade1614d92c6428f5fb895d44",
  created_at: 1700000123,
  kind: 30301,
  tags: [["d", "confidential-1"]],
  content: 'hi "there"\nline2\tsecret unicode e-acute: é',
  sig: "994af3d0edabb47113cbc0c1cf9b600947bdbb242d2a35d6ecc9572fed1fb4f08de337659d5f205e8380159dac8bab9c72755bb2587258783913cb1c31de992d",
};

describe("verifyEvent (Go-generated fixtures)", () => {
  it("accepts a genuine plain board event from the Go signer", () => {
    expect(computeEventId(PLAIN)).toBe(PLAIN.id);
    expect(verifyEvent(PLAIN)).toBe(true);
  });

  it("accepts a genuine event with escaped/unicode content and no title tag", () => {
    expect(computeEventId(CONFIDENTIAL)).toBe(CONFIDENTIAL.id);
    expect(verifyEvent(CONFIDENTIAL)).toBe(true);
    expect(tagValue(CONFIDENTIAL, "title")).toBe("");
  });

  it("rejects a tampered signature", () => {
    const forged = { ...PLAIN, sig: "00" + PLAIN.sig.slice(2) };
    expect(verifyEvent(forged)).toBe(false);
  });

  it("rejects tampered content (id no longer matches)", () => {
    const forged = { ...PLAIN, content: "tampered" };
    expect(verifyEvent(forged)).toBe(false);
  });

  it("rejects a tampered tag (id no longer matches)", () => {
    const forged = { ...PLAIN, tags: [["d", "alpha"], ["title", "Evil Board"]] };
    expect(verifyEvent(forged)).toBe(false);
  });

  it("rejects an event claiming to be authored by a different pubkey", () => {
    const forged = { ...PLAIN, pubkey: "0".repeat(64) };
    expect(verifyEvent(forged)).toBe(false);
  });

  it("rejects a bogus id field even when content/tags/sig are otherwise genuine", () => {
    // This is the one tamper the schnorr check alone would NOT catch: the
    // signed message is always the FRESHLY recomputed canonical id, not
    // whatever the "id" field claims — so a lying id field needs its own
    // explicit stored-id-vs-recomputed-id check (see verifyEvent's first
    // guard). Content/tags/sig here are all real and mutually consistent;
    // only the id field is a lie.
    const forged = { ...PLAIN, id: "0".repeat(64) };
    expect(verifyEvent(forged)).toBe(false);
  });
});
