// GENERATED by web/board/testdata/genportfolio/main.go — DO NOT EDIT BY HAND.
//
//	go run ./web/board/testdata/genportfolio > web/board/src/lib/portfolio.fixtures.ts
//
// A FOUR-BOARD portfolio produced by the REAL Go writer (pkg/sync
// BuildBoardEvent / BuildRoleGrantEvent / BuildCardEvent, pkg/nip44.Seal, the
// ChaCha20-Poly1305 content envelope), for ready-4d9's whole-portfolio link.
// Read the generator's header for the scenario and — importantly — for why
// gamma's cards are sealed under alpha's epoch-1 key.
//
// SECRET KEYS BELOW ARE TEST-ONLY, freshly generated by the run that produced
// this file. Nothing in index.html -> main.ts imports this module, so it is
// never bundled into dist/.

import type { NostrEvent } from "./nostrevent";

export const VIEWER_PUB = "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc";
export const VIEWER_SEC = "07dd1fe95184f3c3dbe2183ddb1057bb843000e0d69d709cb8d4f19477ebebbf";
export const OTHER_OWNER_PUB = "4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137";
export const STRANGER_PUB = "2f8ea5f99c93433804784150aefa606f030c67a2117aa78bf4daae95ab4f49ae";

export const ALPHA_COORD = "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:alpha";
export const BETA_COORD = "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:beta";
export const GAMMA_COORD = "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:gamma";
export const DELTA_COORD = "30301:4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137:delta";

/** Raw CEKs. GAMMA_CEK is deliberately identical to ALPHA_CEK_EPOCH1 — see
 * the generator header's CROSS-BOARD TRAP note: it is what makes a key leaking
 * from one board to another VISIBLE instead of indistinguishable from a failed
 * AEAD. */
export const ALPHA_CEK_EPOCH1 = "01ddb7c24fc287c0a586c6ae6ddf6eb5f69f87aef1fea7f7aeeffffdc6ef0ed3";
export const ALPHA_CEK_EPOCH2 = "12bb976c1ddd652e41ca3a644e1dec2bb530f3b497529b0b5d91e547aa88d556";
export const BETA_CEK = "fc722a995fc3d3adf932169a1d44029b42becf01230a2e08e1ad536f04d26e1e";
export const GAMMA_CEK = "01ddb7c24fc287c0a586c6ae6ddf6eb5f69f87aef1fea7f7aeeffffdc6ef0ed3";
export const DELTA_CEK = "5dc82ff6e351d2a9ee5bf5f70f517358b691fe3e5752b040a361f55a8f59d461";

/** The EXACT `keys=` payload `rd board --portfolio --with-key` prints for
 * this viewer, emitted by the production Go encoder. Covers alpha (both
 * epochs), beta and delta — NOT gamma, which this viewer cannot read. */
export const PORTFOLIO_KEYS_BLOB = "AQIk9XHwHGt_D9nTBlxVMkSl7vroluaznxC88s5Aal7JzAIFYWxwaGECAAAAAQHdt8JPwofApYbGrm3fbrX2n4eu8f6n967v__3G7w7TAAAAAhK7l2wd3WUuQco6ZE4d7Cu1MPO0l1KbC12R5UeqiNVWBGJldGEBAAAAAfxyKplfw9Ot-TIWmh1EAptCvs8BIwouCOGtU28E0m4eT1K6EDe4cWXoBvesakyp1gigvjoykjzd6QZq8qjbETcBBWRlbHRhAQAAAAFdyC_241HSqe5b9fcPUXNYtpH-PldSsECjYfVaj1nUYQ";

/** Every event in the scenario, in relay-delivery order: 4 board definitions,
 * 5 role grants, 8 cards. */
export const snapshot: NostrEvent[] = [
  {
    "id": "a10ee65aa27175ed395f067af9b54c0ecc666b85b86bdc65f365333387dfa8f7",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000000,
    "kind": 30301,
    "tags": [
      [
        "d",
        "alpha"
      ],
      [
        "title",
        "Alpha Board"
      ],
      [
        "p",
        "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ]
    ],
    "content": "",
    "sig": "0bd0ae354badc2b13f7d28131215be37edfd2a7107750fe13fd7b05ca57cb4b9a51563180eac2ee3d921dc3fec19105948d91fb3bad2a05d54c8c9a22758f987"
  },
  {
    "id": "bee48855c7dcd0cdb67aac343c4e08fd7788771749b2cd83f53f48bc76645eeb",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "alpha:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ],
      [
        "p",
        "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:alpha"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AgLp9h1bBNL58h8Th33y+UG6frQf+F7IZgaZo7kh7qEoDmhTIo5pf+EObYVZMjdPZNXYz6YFfbSx1m4GsOoehdoSZMQfdaIc7kkdLbtZF5TnkXLymGKT/dQQqyVreGyqX4/Z3+h6bNeFcWBLf2Pyq0PHwma1853MH0xQyh5eYlVwf88="
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "",
    "sig": "7b6e37b694b0a5d1d33ea982c8082984a7e814f609677ec99d6065ddd38f077126e1eda304da53244c2ffc6d6b00e1a5c18fcdbe383e7c74c777c424a2298b79"
  },
  {
    "id": "6075edf876fe8e7163c7c0b723b29842623df00ef145f2d86bdc531ba9d718c1",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000200,
    "kind": 39301,
    "tags": [
      [
        "d",
        "alpha:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ],
      [
        "p",
        "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:alpha"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AiLzOO+ZH5FGH41MYLXyTYgYzcX6fctec0Xkv/5GRkyLkHMs+vZc1VM6/j+lBHnbJ5qOhppAoHHM9QoshhSwnDi8cNSEplcaOLLxMnpTnF9GDBccskD2EPTq5OLbiGITywu/Xav6v01pbyb31k2ROlgdodikn0YQF5LqcmhJjUpofcY="
      ],
      [
        "cek_epoch",
        "2"
      ]
    ],
    "content": "",
    "sig": "90f50aee7dc236a4fcc4b0fbc14e21ceae28dc1e4c60c9857be61a526307c26eff6a24b34dce5abd9d13b4fb74b793e986bb43ac1ef8d28b76b04a373a172c11"
  },
  {
    "id": "cb05e355d8413a559c3c8f4c7861322c9394f7ad00dcf189e6e8073ed5c0c851",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000300,
    "kind": 30302,
    "tags": [
      [
        "d",
        "alpha-001"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:alpha"
      ],
      [
        "s",
        "active"
      ],
      [
        "rank",
        "p1"
      ],
      [
        "priority",
        "p1"
      ],
      [
        "itype",
        "task"
      ],
      [
        "enc",
        "1"
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "/HZuV1OY4kiL5aGhdEPFrYdIAOiacxRLqHna573FDB9oB8/rV9migiZi5YGvHL0bWALGOt63MhRXvONLR1C82GtaCPtrDCdquvJ+S0U6ClifT4+oFAXoepzT1U82K6oMafkrxA==",
    "sig": "9ab6e6f2301675720c6fbaa337a8be1584225f1858b56dfe17d1f8c8e12fe26888274ee49a33000f3566c0ddc92aba807ec74cdbbfe32294b8c97b8ca90207bf"
  },
  {
    "id": "7eadc368cd89681c5ae3ee2acb1da81c4bb5a81e3bd8a75b91b7ef1649b70636",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000400,
    "kind": 30302,
    "tags": [
      [
        "d",
        "alpha-002"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:alpha"
      ],
      [
        "s",
        "inbox"
      ],
      [
        "rank",
        "p2"
      ],
      [
        "priority",
        "p2"
      ],
      [
        "itype",
        "task"
      ],
      [
        "enc",
        "1"
      ],
      [
        "cek_epoch",
        "2"
      ]
    ],
    "content": "xsizrqxc7dwDKyGa6retZ4BYJA9bqwtTAqLtftfvFT0MLBSbyQt/zpSVdoBnJAwZDOOMro1t0RqJN87yxGf8RXGY+DbnWSD1B4ocD52msOQfDSEJJF4OJVDtAapzNfcHny9ssrMhW+0=",
    "sig": "c9ceaaedb5b21656c64de352b302a783528b2a53dccd57279f15e8f49a4110637ad442e49c3d3bc1ce6c86611f7770c253e6fbba268794924a11f26ad07b1342"
  },
  {
    "id": "91d6b0ca091e88915f7da68f5ed0a3e7b0fadffd884b8a997557356d35823d1e",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000000,
    "kind": 30301,
    "tags": [
      [
        "d",
        "beta"
      ],
      [
        "title",
        "Beta Board"
      ],
      [
        "p",
        "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ]
    ],
    "content": "",
    "sig": "a94987dc7451b276c98266109d990869ec10281a7bed70ecdd07af5a9c0f1e3fb6612a576360e6ec76ec5b853a43b55bafaf0a8966c6daf235ef1e1b5ba38c05"
  },
  {
    "id": "d249e511fd8ac7fe1fdffcf7194d300241225d9cf02c51ff5073c150bb7083e1",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "beta:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ],
      [
        "p",
        "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:beta"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AkuJgtWC6AXZrjNg2CU9k/9rhLJ1Brx3SwccEZaV6ie6ngIwSLzHJBLpN5J32wPdmMKqMmWpIiXZE4clRu2siofJO7FudPfW8Xcp2I6Mb9N/YN+IL9jLnTEJCH1jKcSTq1TrXRGUNw8xNfvmbP9076FVM+FIlVY7e1KsZHGIlK0DRL4="
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "",
    "sig": "7a8e5346176de39a2db1187c6c94a4c6eecb07b6289fe3625ba8b0a8fb45eebf6ec5c3ef53993806c12064795a1539a7bdb607b3c64ae7b38530d3d047a59449"
  },
  {
    "id": "8f1be4d268f9bb86f10acc831c754e0acd227ff3354d90d5757626a44f90f388",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000300,
    "kind": 30302,
    "tags": [
      [
        "d",
        "beta-001"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:beta"
      ],
      [
        "s",
        "active"
      ],
      [
        "rank",
        "p0"
      ],
      [
        "priority",
        "p0"
      ],
      [
        "itype",
        "decision"
      ],
      [
        "enc",
        "1"
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "0iRKxWnEB9MvWSrTKBNqcOWta8s7rhvnt/VlKfzAFwyIK3RPzzKqU7w0bY/5vBNWsBE0qq9eo+KP1MKwI+x0mBKf5507+VgzdZFBkN4ChepQp90evRfvJiGKgJIzpQ==",
    "sig": "ed390e23ce50e79dbf06a04df2544c99d0d254e78c92c24759b33e13cded385ceabf683017c59327df58ea46c2c3b3b19461525b42927c79cdeaf621838b205f"
  },
  {
    "id": "ebf33d7ed22d0b8115b0644ca1b2949ea30d382d1b09b93bd939efc70741848c",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000000,
    "kind": 30301,
    "tags": [
      [
        "d",
        "gamma"
      ],
      [
        "title",
        "Gamma Board"
      ],
      [
        "p",
        "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ]
    ],
    "content": "",
    "sig": "054d07120ae4a69333f90e8080fe25beb2a446219eedc34e36af568bfd1f6d9bf5a98237addd59ae2bbb9591966f59ec6f3f21368971bfecccf1ce5c31d9c78b"
  },
  {
    "id": "be91b2a35e76027dec66e9ed3e314f859cd97f54421eeb586d16a8e7bd2c3d76",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "gamma:2f8ea5f99c93433804784150aefa606f030c67a2117aa78bf4daae95ab4f49ae"
      ],
      [
        "p",
        "2f8ea5f99c93433804784150aefa606f030c67a2117aa78bf4daae95ab4f49ae"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:gamma"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "AgR/+dfXAXotB4eDEefUuquZ+mIzdFVpKvLS0JvWCGmHFZ2EN3xmWr1XkgJVXLTsi8iqcwiOIbyFEtmhst0mxvqI4VH4BJYrqc3vY8kYApF9ThOaG29ZNll0ZY8xTmo8jRCXEG2F4QuUUuVXaTzAW4MymZroOeyzLWsy85Yv7ZRNPfo="
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "",
    "sig": "016794f02601fa0894245539808ff819652002da0e4e064e108ad0e1acf53cb9584c0c878b3446d624febae83758d5e9ffe751b83d8cf18ddd0b5cfd37630ac4"
  },
  {
    "id": "86c0ba16571f281ce4574730eb95ef0a81e3fc3311a62ce604f78af36f775155",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000300,
    "kind": 30302,
    "tags": [
      [
        "d",
        "gamma-001"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:gamma"
      ],
      [
        "s",
        "active"
      ],
      [
        "rank",
        "p1"
      ],
      [
        "priority",
        "p1"
      ],
      [
        "itype",
        "task"
      ],
      [
        "enc",
        "1"
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "5GYBuPxnhrNclxIcb642d6e7wFEPTmFlSnFoYNp9J7uGc2HtJGLqWVQip4bOyrT1Zonp2YCUEvbunWO9Cvhbr4Glfh9b2kZhfotbVa5qM9rXv5MlRPilKw==",
    "sig": "9206edef855bc0e7e8998786c681d7bc212834c4a1a1b056350632616f555cb6d5e23637d61d8df48fee7122372ff9f5f5d604cdb666d8e12b9def0b9cdf585d"
  },
  {
    "id": "8ca2a92879495c35a383a3a66b69845456a27f3fc7d000662ad963703869b6d3",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1759999000,
    "kind": 30302,
    "tags": [
      [
        "d",
        "gamma-002"
      ],
      [
        "title",
        "Gamma legacy plaintext"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:gamma"
      ],
      [
        "s",
        "inbox"
      ],
      [
        "rank",
        "p3"
      ],
      [
        "priority",
        "p3"
      ],
      [
        "itype",
        "task"
      ]
    ],
    "content": "Authored before gamma went confidential.",
    "sig": "724824b86cc19e5ca1eeafddf70116f75dd7121c83b9c5d35d89ddfb78f0b0216783c5dc9f07f2d0c41928cab7abf8ec7d91f89b1f35ac07874867a133545e45"
  },
  {
    "id": "b96c2b7031a8423629ffbfea83657f74095edb87d79b3ba5244b783209b64144",
    "pubkey": "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc",
    "created_at": 1760000500,
    "kind": 30302,
    "tags": [
      [
        "d",
        "gamma-003"
      ],
      [
        "title",
        "GAMMA SMUGGLED CLEARTEXT"
      ],
      [
        "a",
        "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:gamma"
      ],
      [
        "s",
        "active"
      ],
      [
        "rank",
        "p1"
      ],
      [
        "priority",
        "p1"
      ],
      [
        "itype",
        "task"
      ]
    ],
    "content": "GAMMA SMUGGLED BODY",
    "sig": "21c082b51cbaa3e65f5810631f587d5f1ad89fdfd1dacac8bd16750cad9ac9922c165e96b83f3e81a80d0a69f838b113a425ff97278899a9b84af84974cfa1bf"
  },
  {
    "id": "59c5df7488c19c0162eba7401646d0cf614e21297e3ce05d4d97eba27034c807",
    "pubkey": "4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137",
    "created_at": 1760000000,
    "kind": 30301,
    "tags": [
      [
        "d",
        "delta"
      ],
      [
        "title",
        "Delta Board"
      ],
      [
        "p",
        "4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137"
      ]
    ],
    "content": "",
    "sig": "7ce2a3710713b1d1177bf6e28fa8947a2f89d298fffc0a68b386a5370cc1f6c7955efe35e146281b73d097a68d007f2ddc7f00bb2f30600624bea42933381e75"
  },
  {
    "id": "6307c78b48f9378d7aa282fa0f691d196a724f9029519c0e305939da91f439b8",
    "pubkey": "4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137",
    "created_at": 1760000100,
    "kind": 39301,
    "tags": [
      [
        "d",
        "delta:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ],
      [
        "p",
        "24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc"
      ],
      [
        "a",
        "30301:4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137:delta"
      ],
      [
        "role",
        "owner"
      ],
      [
        "cek",
        "Apwe8sgSqE/9Y8I9C89kvW7Z7ehbv8XJjvPZz2CB+cv9HiMkFdbBn9too/ADtZZS/ryWvk6rPpymZgS2FKY690TaQ65Je9N1nl68XS8UBUBN+SiSJzzKkpAT5H04a8ASBBivMcZcPMt3G1DezuEmLdDmRV89VnmrlvknrTuuLVnAdkI="
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "",
    "sig": "ab707e116d7fc5ac62d5e97fc1adb4841eb2b94e7500ba190a8f738cfe66baa87993ecf986ea39a45f9e023a1aba179783e798aee4e1e1377dd89c29eb75add0"
  },
  {
    "id": "83d5c3355fa689a91de4b5782e9af117451b5dc6bdde0fb3001ecf364627094f",
    "pubkey": "4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137",
    "created_at": 1760000300,
    "kind": 30302,
    "tags": [
      [
        "d",
        "delta-001"
      ],
      [
        "a",
        "30301:4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137:delta"
      ],
      [
        "s",
        "active"
      ],
      [
        "rank",
        "p1"
      ],
      [
        "priority",
        "p1"
      ],
      [
        "itype",
        "task"
      ],
      [
        "enc",
        "1"
      ],
      [
        "cek_epoch",
        "1"
      ]
    ],
    "content": "ErBzCC+7cRqu7CCb9Y2FEtZxXfazGMZzUAgXyTZLbNXwv3qgjNq1W4YkYFMvtv+ffxWVMJqA7vuNibJh4iW3yySX8z/0AfDWXU4S30i5ZphhMCcLYOKQ4zlAm0714G1PCQf1",
    "sig": "a46b51dbd034663a3e060e2340c1e2fabaafbb19fcb5cededaa49cc47d73e4a2b1b61af23b13a4fc43a27c328f799d9ba7868783ffdec78b68eaa42d134467c8"
  }
];

/** The plaintext the Go writer sealed on the boards the viewer CAN read. */
export const expectedPlaintext = [
  {
    "id": "alpha-001",
    "title": "Alpha epoch one card",
    "coord": "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:alpha"
  },
  {
    "id": "alpha-002",
    "title": "Alpha after the rotation",
    "coord": "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:alpha"
  },
  {
    "id": "beta-001",
    "title": "Beta board card",
    "coord": "30301:24f571f01c6b7f0fd9d3065c553244a5eefae896e6b39f10bcf2ce406a5ec9cc:beta"
  },
  {
    "id": "delta-001",
    "title": "Delta board card",
    "coord": "30301:4f52ba1037b87165e806f7ac6a4ca9d608a0be3a32923cdde9066af2a8db1137:delta"
  }
] as const;

/** Titles and bodies that must NEVER appear in the DOM for this viewer: gamma
 * is confidential and the viewer holds no key for it, and its post-cutover
 * cleartext card is quarantined by the fold gate. */
export const forbiddenText = [
  "GAMMA SECRET TITLE",
  "GAMMA SECRET BODY",
  "GAMMA SMUGGLED CLEARTEXT",
  "GAMMA SMUGGLED BODY",
] as const;
