// Command genportfoliovectors emits web/board/testdata/portfolio-key-vectors.json:
// the cross-language conformance vectors for the `keys=` portfolio blob
// (ready-4d9).
//
//	go run ./web/board/testdata/genportfoliovectors > web/board/testdata/portfolio-key-vectors.json
//
// Each vector pairs an INPUT (board coordinate -> epoch -> 64-hex CEK) with the
// base64url blob the REAL encoder — pkg/sync.EncodePortfolioKeyBlob, the same
// function `rd board --portfolio --with-key` calls — produces for it. There is no
// second copy of the encoding anywhere in this file.
//
// Go asserts encode(input) == blob (pkg/sync/portfolioblob_test.go); the browser
// asserts decode(blob) == input (web/board/src/lib/portfoliokeys.test.ts).
// Neither side regenerates this file during a test run, so a change to either
// implementation alone turns its own suite red instead of both quietly agreeing
// on new bytes.
//
// The key material is deterministic filler, not minted keys: these vectors pin an
// ENCODING, and random keys would churn the committed file on every regeneration
// for no added coverage.
package main

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"

	rdSync "github.com/3dl-dev/ready/pkg/sync"
)

type vector struct {
	Name string `json:"name"`
	// Boards is coordinate -> epoch (decimal string, because JSON object keys
	// are strings) -> 64-hex CEK.
	Boards map[string]map[string]string `json:"boards"`
	Blob   string                       `json:"blob"`
}

func fill(b byte) string {
	var k [32]byte
	for i := range k {
		k[i] = b + byte(i)
	}
	return hex.EncodeToString(k[:])
}

const ownerA = "d2f6e78d61e5a57df834b1fa4b8ab8dff7f3ab4414fc6167698ad7f25b2568f5"
const ownerB = "3be7a22c2cc01e01a87cf24ce1f528800715787ec1af5833cc1875cb51ef8091"

func main() {
	vs := []vector{
		{
			Name:   "one board, one epoch",
			Boards: map[string]map[string]string{"30301:" + ownerA + ":ready": {"1": fill(0x11)}},
		},
		{
			Name:   "one board, two epochs (a rotated board)",
			Boards: map[string]map[string]string{"30301:" + ownerA + ":ready": {"1": fill(0x21), "2": fill(0x31)}},
		},
		{
			Name: "two boards, same owner",
			Boards: map[string]map[string]string{
				"30301:" + ownerA + ":ready":     {"1": fill(0x41)},
				"30301:" + ownerA + ":galtrader": {"1": fill(0x51), "3": fill(0x61)},
			},
		},
		{
			Name: "two owners — a board granted to this key by someone else",
			Boards: map[string]map[string]string{
				"30301:" + ownerA + ":ready": {"1": fill(0x71)},
				"30301:" + ownerB + ":forge": {"2": fill(0x81)},
			},
		},
		{
			Name:   "a d-tag containing a colon (coordinates split into exactly 3, so it survives)",
			Boards: map[string]map[string]string{"30301:" + ownerA + ":odd:board": {"1": fill(0x91)}},
		},
		{
			Name:   "a non-ASCII d-tag (the length prefix counts BYTES, not runes)",
			Boards: map[string]map[string]string{"30301:" + ownerA + ":propriété": {"1": fill(0xa1)}},
		},
		{
			Name:   "an epoch above 65535 (the epoch field is 4 bytes, not 2)",
			Boards: map[string]map[string]string{"30301:" + ownerA + ":ready": {"70000": fill(0xb1)}},
		},
		portfolio24(),
	}

	out := make([]vector, 0, len(vs))
	for _, v := range vs {
		blob, err := rdSync.EncodePortfolioKeyBlob(toKeys(v.Boards))
		if err != nil {
			fmt.Fprintf(os.Stderr, "vector %q: %v\n", v.Name, err)
			os.Exit(1)
		}
		v.Blob = blob
		out = append(out, v)
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(map[string]any{
		"_comment": "GENERATED by web/board/testdata/genportfoliovectors — DO NOT EDIT BY HAND. See that command's header.",
		"vectors":  out,
	}); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// portfolio24 is the SIZE case: a realistic whole-portfolio link (24 boards, one
// owner, one epoch each). Both suites assert on the length of the link it
// produces — a link too long for the channel it travels through is the failure
// mode this format exists to survive.
func portfolio24() vector {
	names := []string{
		"ready", "rudi", "galtrader", "forge", "dontguess", "website", "aerocloak", "vms",
		"producer", "3dl", "agentic-internet", "agentic-internet-ops", "3dl-infra-aws",
		"mallcop-pro", "automata-island", "campfire", "campfire-hosting", "campfire-marketplace",
		"beads", "clankeros", "practice", "blog", "ops", "sandbox",
	}
	sort.Strings(names)
	boards := map[string]map[string]string{}
	for i, n := range names {
		boards["30301:"+ownerA+":"+n] = map[string]string{"1": fill(byte(i + 1))}
	}
	return vector{Name: "24 boards, one owner, one epoch each (the real portfolio size)", Boards: boards}
}

// toKeys converts the JSON-shaped vector input into the encoder's argument type.
func toKeys(boards map[string]map[string]string) map[string]map[int][32]byte {
	out := map[string]map[int][32]byte{}
	for coord, epochs := range boards {
		m := map[int][32]byte{}
		for epStr, h := range epochs {
			ep, err := strconv.Atoi(epStr)
			if err != nil {
				panic(fmt.Sprintf("vector epoch %q: %v", epStr, err))
			}
			raw, err := hex.DecodeString(h)
			if err != nil || len(raw) != 32 {
				panic(fmt.Sprintf("vector cek %q is not 32 bytes of hex", h))
			}
			var k [32]byte
			copy(k[:], raw)
			m[ep] = k
		}
		out[coord] = m
	}
	return out
}
